### ISSUE TITLE
Failed on a dynamic ELF without rela.dyn

### ISSUE THREAD

**Issue by viric** [NixOS/patchelf#1]
Hello,

I've a dynamically linked binary (it has rpath, it has interpeter), on linux x86_64, that lacks rela.dyn. Patchelf complains as if it couldn't do anything with the binary because it lacks rela.dyn.

The binary comes prebuilt from a software distributor, and I don't have access to its source or its build recipes.

Could patchelf be made to work without rela.dyn section?

**Comment by darealshinji** [comment]
I think this PR would fix that: https://github.com/NixOS/patchelf/pull/40
