### ISSUE TITLE
Some rpath checks fail when run on aarch64/ppc64le/ppc64

### ISSUE THREAD

**Issue by nullr0ute** [NixOS/patchelf#105]
Same group of tests fail when run on these three arches (works fine on x86, x86_64, armv7 and s390x though

make[3]: Entering directory '/builddir/build/BUILD/patchelf-0.9/tests'
PASS: plain-fail.sh
PASS: plain-run.sh
PASS: shrink-rpath.sh
PASS: set-interpreter-short.sh
PASS: set-interpreter-long.sh
PASS: set-rpath.sh
PASS: no-rpath.sh
PASS: big-dynstr.sh
PASS: set-rpath-library.sh
PASS: soname.sh
PASS: no-rpath-amd64.sh
FAIL: no-rpath-armel.sh
FAIL: no-rpath-armhf.sh
FAIL: no-rpath-hurd-i386.sh
FAIL: no-rpath-i386.sh
PASS: no-rpath-ia64.sh
PASS: no-rpath-kfreebsd-amd64.sh
FAIL: no-rpath-kfreebsd-i386.sh
PASS: no-rpath-mips.sh
PASS: no-rpath-mipsel.sh
PASS: no-rpath-powerpc.sh
PASS: no-rpath-s390.sh
PASS: no-rpath-sh4.sh
# PASS: no-rpath-sparc.sh
# Testsuite summary for patchelf 0.9
# TOTAL: 24
# PASS:  19
# SKIP:  0
# XFAIL: 0
# FAIL:  5
# XPASS: 0
# ERROR: 0
# 
# See tests/test-suite.log

**Comment by domenkozar** [comment]
Passes on master https://nix-cache.s3.amazonaws.com/log/fmxcpr5wiqrjh1n5z3k3i6mf5wva7knb-patchelf-0.11.20200609.d6b2a72.drv
