### ISSUE TITLE
Running patchelf on a dynamic executable causes a segfault

### ISSUE THREAD

**Issue by probonopd** [NixOS/patchelf#110]
As part of my `linuxdeployqt` build process (Travis CI log files below) I am using patchelf. However, the `linuxdeployqt` command does not run anymore thereafter. It just segfaults. I am attaching the binaries.

```
me@host:~$ file linuxdeployqt 
linuxdeployqt: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=f4089ff93f4385b4789ee518c9c7a513660faf85, not stripped

me@host:~$ patchelf --print-interpreter linuxdeployqt
/lib64/ld-linux-x86-64.so.2

me@host:~$ patchelf --print-rpath linuxdeployqt
$ORIGIN/../lib/

me@host:~$ /patchelf --print-needed linuxdeployqt
libQt5Core.so.5
libpthread.so.0
libstdc++.so.6
libgcc_s.so.1
libc.so.6

Build log (stripped):
https://travis-ci.org/probonopd/linuxdeployqt/builds/181106034

Build log (unstripped):
https://travis-ci.org/probonopd/linuxdeployqt/builds/181094642
```

* [stripped-linuxdeployqt-segfaults.zip](https://github.com/NixOS/patchelf/files/629455/stripped-linuxdeployqt-segfaults.zip)
* [unstripped-linuxdeployqt-segfaults.zip](https://github.com/NixOS/patchelf/files/629454/unstripped-linuxdeployqt-segfaults.zip)

**Comment by probonopd** [comment]
May be caused by #124

**Comment by domenkozar** [comment]
@probonopd I'd appreciate if you can use patchelf master to confirm this is fixed.

**Comment by Mic92** [comment]
Closing because lack of feedback.
