### ISSUE TITLE
Add tags for latest releases

### ISSUE THREAD

**Issue by dan-blanchard** [NixOS/patchelf#14]
The last version tag is for 0.6, but it looks like 0.8 is the most recent release. Could you please add the tags for 0.7 and 0.8?

**Comment by fsateler** [comment]
I see 0.7 and 0.8 tags here. Maybe this should be closed?

**Comment by dan-blanchard** [comment]
Wow, I forgot I even filed this issue.  Glad to see it's been fixed!
