### ISSUE TITLE
set-rpath-library.sh test failure w/musl

### ISSUE THREAD

**Issue by dtzWill** [NixOS/patchelf#147]
Test skipped in nixpkgs expression when using musl as a result:

https://github.com/NixOS/nixpkgs/commit/c0d343bc5ff08078356080f821af3d0d101d4092

Here's the build log, FWIW:

https://gist.github.com/dtzWill/3852581fceca47f2680e2c5890159659

LMK if any additional details or help reproducing would be useful.

--------

The following reproduces the problem (although you may need to build a musl stdenv first :3)

```console
$ $ nix build -f https://github.com/dtzWill/nixpkgs/archive/patchelf-unstable-musl-repro.tar.gz patchelfUnstable --arg localSystem '{config="x86_64-unknown-linux-musl";}'
```

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/patchelf/pull/104 and hope to catch these early in https://github.com/NixOS/patchelf/pull/205
