### ISSUE TITLE
--set-soname corrupts binary if the original soname string is also used for symbol versioning

### ISSUE THREAD

**Issue by mayeut** [NixOS/patchelf#155]
Seen with NVIDIA CUDNN 7.1.4 for CUDA 9
Symbols are versioned using the SONAME i.e. libcudnn.so.7
When setting a new SONAME , all symbols become versioned with XXXXXXXXXXXXX

When commenting the following line, symbol version are correct.
https://github.com/NixOS/patchelf/blob/27ffe8ae871e7a186018d66020ef3f6162c12c69/src/patchelf.cc#L1080

I don't know the implication of commenting this line of code so not opening a PR and letting someone more enlightened on the subject follow-up on this.

Simple reproducer:
`lib.c`:
```
int exportedSymbol(int a) {
	return a;
}
```
`liblib.map`:
```
liblib.so.1 {
  global:
    exportedSymbol;

  local:
    *;
};
```
`script`:
```
gcc -shared -o liblib.so.1.0.0 -Wl,-soname,liblib.so.1 -Wl,--version-script=liblib.map lib.c
patchelf --set-soname liblib-abcd.so.1 liblib.so.1.0.0
```

This was tested in a quay.io/pypa/manylinux1_x86_64 docker container.

**Comment by dezgeg** [comment]
This has happened before: https://github.com/NixOS/patchelf/issues/45#issuecomment-294801888

**Comment by lkollar** [comment]
This is causing issues in `auditwheel` as reported in https://github.com/pypa/auditwheel/issues/159. Removing this "zeroing out" logic from `patchelf` fixes the issue. Does anybody know why this logic is necessary?

**Comment by njsmith** [comment]
I think the memset is probably unnecessary, and only included to help catch any places where the soname was accidentally still used. Now we've discovered that it can be *intentionally* still used, so maybe it's best to remove the memset...

I guess the other option would be to explicitly check for any usage in the symbol table, and either rewrite those, or conditionally disable the memset only in cases where the soname is used as a version. But that's a lot more complicated than just deleting the memset.
