### ISSUE TITLE
opetion suggestion :: --append-rpath 

### ISSUE THREAD

**Issue by EricDeveaud** [NixOS/patchelf#163]
Hello, 

sorry for the typo in title.... 
s/opetion/option/

I have sometime the need to add some location to binaries//libs that already have rpath set 

in this case I usually do the following, let say foo is the binary I want to deal with

```
patchelf --set-rpath '/some/path/to/lib:'$(patchelf --print-rpath foo) foo
```

would you consider adding a otion to perform this task in an easy way.  
eg:
```
patchelf --append-rpath '/some/path/to/lib' foo
```

regards

Eric

**Comment by domenkozar** [comment]
Duplicated #184
