### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by lkollar** [NixOS/patchelf#174]
The `auditwheel` project is a prominent user of `patchelf` and we have identified several bugs in `patchelf` in the past which impacts (or impacted in the past) the project. `patchelf` seems to move fairly slow which means that we have to resort to workarounds while waiting for bug fixes to be merged and released -- in the past we've shipped a custom build of `patchelf` in the `manylinux` images or applied workarounds in `auditwheel` in the code until it's fixed in `patchelf` (https://github.com/NixOS/patchelf/issues/94).

We started [discussing](https://github.com/pypa/auditwheel/issues/174) options to improve the situation. One thing we could do is to help out maintaining `patchelf`. If we can get issues fixed and patches landed quicker and do releases more frequently it could benefit both projects. I am happy to volunteer helping out and there might be more @pypa folks who are interested in chipping in.

If there are other ways you think we can help out with `patchelf`, please let us know.

**Comment by probonopd** [comment]
> `patchelf` seems to move fairly slow which means that we have to resort to workarounds while waiting for bug fixes to be merged and released -- in the past we've shipped a custom build of `patchelf`

Same here, awaiting a fix for https://github.com/NixOS/patchelf/issues/124 since 2 years. Would be great if you could help to bring this tool up to speed :+1:

**Comment by edolstra** [comment]
Thanks! It would definitely be good to have more maintainers for patchelf, since I have little time for it myself at the moment.

**Comment by dasJ** [comment]
So what about this? I'd really love to see some development on this project

**Comment by lkollar** [comment]
I've been busy with some other stuff, but I'm planning to have a look at the test suite and improve it so that the existing bug reports can be reproduced and we can avoid regressions in the future. Hopefully by having a more robust test suite we can simplify contributions and speed things up a bit.

**Comment by lkollar** [comment]
As a quick experiment I replaced the `patchelf` code in `auditwheel` with LIEF and it works perfectly for my use case, so while I'm still interested in helping out, given that it's a lot less work to simply integrate LIEF into the code base and I can use the extra time on `auditwheel` itself, I won't be able to dedicate as much time to `patchelf` as I hoped to. 

Given that there seems to be interest in getting more maintainers I think it would be useful to put out a call on mailing lists and other channels to get more attention on the issue.

**Comment by probonopd** [comment]
> LIEF

Thanks for the hint.
In case someone wonders what LIEF is: https://lief.quarkslab.com/doc/latest/Intro.html

**Comment by domenkozar** [comment]
See https://github.com/NixOS/patchelf/issues/199
