### ISSUE TITLE
cannot find section .interp

### ISSUE THREAD

**Issue by iamsunxing** [NixOS/patchelf#176]
patchelf --set-interpreter ./libs/ld-linux-x86-64.so.2 libXXX.so 
cannot find section .interp

**Comment by sjackman** [comment]
Dynamic libraries don't have a dynamic interpreter. Only dynamic executables have a dynamic interpreter.

**Comment by iamsunxing** [comment]
> Dynamic libraries don't have a dynamic interpreter. Only dynamic executables have a dynamic interpreter.
Thank you for your reply. there is another problem:
In my work platform(ubuntu 18.04 lts):
using "patchelf --set-rpath ./libs libXXX.so"
$ldd libXXX.so                              
        linux-vdso.so.1 (0x00007fffc0fc5000)
        libm.so.6 => ./libs/libm.so.6 (0x00007f4e43bb3000)
        libc.so.6 => ./libs/libc.so.6 (0x00007f4e437c2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4e44404000)
copy libXXX.so to the target platform(centos):
using the python to call:
encounter a error:
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by libXXX.so)
that is to say: libXXX.so don't call the ./libs/libm.so.6 
where am I doing something wrong?

**Comment by sjackman** [comment]
> `patchelf --set-rpath ./libs libXXX.so`

RPATH must be an absolute path name (`./libs` is a relative path name), or you can use token expansion, like `$ORIGIN/libs`. See `Rpath token expansion` in `man ld.so` http://man7.org/linux/man-pages/man8/ld.so.8.html

**Comment by domenkozar** [comment]
Closing as wontfix.

**Comment by git801** [comment]
> Dynamic libraries don't have a dynamic interpreter. Only dynamic executables have a dynamic interpreter.

![2](https://user-images.githubusercontent.com/68671356/226563761-8f6cf504-1b09-46d2-9202-fde8ece85d5c.PNG)

` patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 libpython3.6m.so.1.0
`    return cannot find section .interp
` patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 test-tool
`    no use

I would like to run a elf that needs many libraries,like the ieeue here

[https://github.com/NixOS/patchelf/issues/486](url)

May you give me a hand , thank you so much
