### ISSUE TITLE
Suggestion: small patch to enable compilation with pre-4.7 g++

### ISSUE THREAD

**Issue by Giraut** [NixOS/patchelf#179]
I've had to compile patchelf on an old machine for a special project involving support on legacy Linux boxes with a wide range of kernel versions and libc versions.

For various reasons, I had to use g++ version 4.6.3, that doesn't understand c++11. So I patched the code to compile it with c++0x. Since it takes very few changes to make patchelf compatible with older compilers, I suggest the attached patch:

[patchelf-g++_pre-4.7.txt](https://github.com/NixOS/patchelf/files/3509845/patchelf-g%2B%2B_pre-4.7.txt)

**Comment by edolstra** [comment]
Hm, I'd really prefer not to restrict ourselves to C++98 in 2019 :-)

**Comment by Giraut** [comment]
Well, I suggested this because the only change required to the code to make it fully backward-compatible is moving the initialization away from the declaration for 3 class variables, which is fairly minor and of no consequence to anything else. As for the Makefile.am, it doesn't really need patching: if someone ever has the same need I had, they can change the -std flag themselves. But at least with the minor code change then the code would compile straightaway if they do.

But all in all, this is completely non-important, and I totally get your comment :)
