### ISSUE TITLE
patchelf core dumps on warsaw binaries

### ISSUE THREAD

**Issue by romildo** [NixOS/patchelf#190]
I want to package warsaw in NixOS.

Warsaw is a security solution developed by GAS Software that is used by most banks (in Brazil) that do not use Java technology to authenticate Internet Banking users.

PR https://github.com/NixOS/nixpkgs/pull/76636 is my attempt in doing so.

Unfortunatly `patchelf` is failing and core dumping, and I do not know how to proceed?

Any clues?

**Comment by domenkozar** [comment]
This was fixed in https://github.com/NixOS/patchelf/commit/daaffbe7f3e4e1ec0052f8d6ce153cd7f5fdeb76 and released as par of 0.10, but Nixpkgs still uses 0.9 until 0.11 is released with #170
