### ISSUE TITLE
Crashes with invalid binaries using fuzzing

### ISSUE THREAD

**Issue by Mindavi** [NixOS/patchelf#194]
Hi, I've done some fuzzing against patchelf to hopefully improve the quality of this tool. The crashing inputs all cause a segfault with the following command `patchelf --set-interpreter /abc/def/ghi.so INPUT_FILE`. Hopefully this helps improving the tool to handle invalid input. I assumed the assertions failing wouldn't matter, so I remove all inputs that caused assertion errors. If I should attach them, let me know.

[inputs.zip](https://github.com/NixOS/patchelf/files/4210917/workdir.zip)

The used binary (fuzzing input) is a very simple binary with the following source code, if anyone wants to reproduce:

```
int main() {
  return 1;
}
```

Used fuzzer is american fuzzy lop.

**Comment by domenkozar** [comment]
@Mindavi would be great if you can open a PR adding a regression test to tests directory.

**Comment by Mindavi** [comment]
I'd like to add one or more regression tests, but it would be good to categorize them on what exactly goes wrong. However, I'm not too well versed in the file format of ELF binaries to decide why it's crashing. The only thing I know is that the attached directory contains a corpus of files that crash patchelf in a non-graceful way (`assert()`-ing on invalid/unhandled input is better than segfaulting).

I will look into sorting out unique crashes and point out which line(s) seem to be offending, maybe you (or someone looking at this) can then help finding out what the regression is and help building a categorized regression suite :).

Of course, I could only categorize them on which source code is hit and split it into distinct black-box tests. That'd help on the short term by showing what's wrong (the tests could link to the possibly offending source), but long-term it would be good to describe why the regressions are as they are.

I'll update whenever I've made a start on categorizing and finding out which crashes are unique -- I'm sure there will be some duplicates in the corpus.

**Comment by Mindavi** [comment]
Haven't checked, but presumably #251 fixes these issues, as I also only did a shallow fuzzing run, nothing too deep.
