### ISSUE TITLE
--set-interpreter doesn't work as it should

### ISSUE THREAD

**Issue by Th3R4nd0m** [NixOS/patchelf#195]
I have an ELF binary named "random", and I want to change the loader.

 ldd random
`linux-vdso.so.1 (0x00007ffce9294000)`

`libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd7dd472000)`

`/lib64/ld-linux-x86-64.so.2 (0x00007fd7dd863000)`

We run 
> patchelf --set-interpreter /tmp/ld-2.23.so ./random

and we run ldd again
`linux-vdso.so.1 (0x00007ffce9294000)`

`libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd7dd472000)`

`/tmp/ld-2.23.so => /lib64/ld-linux-x86-64.so.2 (0x00007fd7dd863000)`

I try to run the binary with LD_PRELOAD=./libc.so.6 ( 2.23), and I get a segfault.
I worked 2 weeks ago :(

**Comment by Th3R4nd0m** [comment]
Wrong, I'm just stupid.

**Comment by champagneo** [comment]
What happen actually? I get the same mistake！
