### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by domenkozar** [NixOS/patchelf#199]
Given that @edolstra is quite busy and this project has grown beyond only Nix community, it would be wise to accept new maintainers to help out.

Once we have more maintainers, one of the goals to move faster and break less things would be to setup regression tests with the binaries.

I'd appreciate if developers would describe a few words what are they working on with patchelf and why they'd help maintain it.

**Comment by auvipy** [comment]
as a maintainer of auditwheel, this interests me.

**Comment by domenkozar** [comment]
0.11 was just released today with a bunch of patches.

**Comment by mattip** [comment]
sorry to be a bother, but it seems manylinux needs 0470d69 to correctly patch arm64 objects. This is causing problems, see pypa/manylinux#735. Is there a plan for a release with this patch, or should we patch locally?

**Comment by domenkozar** [comment]
0.12 was released yesterday

**Comment by mattip** [comment]
Thanks!

**Comment by Mic92** [comment]
I would like to apply as a maintainer. I have written my own link-loader for glibc's LD: https://github.com/Mic92/nix-ld
and in my current work (paper not published yet) I relocate a shared library against a guest kernel that runs inside VM (https://github.com/Mic92/vmsh)

**Comment by edolstra** [comment]
@Mic92 Thanks! I've given you maintainer access to the patchelf repo.

**Comment by Mic92** [comment]
Number of open PRs goes down. I think project is good for now.
