### ISSUE TITLE
Assertion `pos + t.size() <= s.size()' failed

### ISSUE THREAD

**Issue by manveru** [NixOS/patchelf#207]
**Describe the bug**

While trying to do a patchelf on `electron.debug`, I get a strange error:

```
patchelf: patchelf.cc:1028: void setSubstr(std::string&, unsigned int, const string&): Assertion `pos + t.size() <= s.size()' failed.
```

**Steps To Reproduce**

Warning, this will download over a gigabyte of data just for the electron binary alone...

```
git clone https://github.com/manveru/nix-electron-issue
nix-build ./nix-electron-issue
```

**Expected behavior**

The binary gets patched.

**`patchelf --version` output**
`patchelf 0.10`

**Additional context**

patchelf works on the production/stripped version of electron, however I'm trying to debug a SIGTRAP happening within that and without symbols i cannot decipher the gdb backtrace.

**Comment by DerDakon** [comment]
Since this function is called from several places a backtrace would be helpful.

**Comment by domenkozar** [comment]
Could you try v0.13?

**Comment by Mic92** [comment]
Closing because of lack of feedback.

**Comment by Mic92** [comment]
Potentially same as https://github.com/NixOS/patchelf/issues/305
