### ISSUE TITLE
Include ./configure in the release tarball

### ISSUE THREAD

**Issue by sjackman** [NixOS/patchelf#211]
**Is your feature request related to a problem? Please describe.**
Running `./bootstrap.sh` requires `autoconf` and `automake`, which may not be available.

**Describe the solution you'd like**
Include `./configure` in a release asset tarball, built with `make distcheck`.

**Describe alternatives you've considered**
Installing `autoconf` and `automake`.

**Additional context**
Homebrew uses `patchelf` to install its prebuilt binary packages (bottles), and `patchelf` is the very first package installed on a system, so at this point no other dependencies are installed. It's easier to bootstrap a system if `patchelf` has no dependencies. The version 0.10 tarball included `./configure` and had no dependencies.

As a bonus, GitHub does not count the number of downloads of its automatically generated tarballs, but it does count the number of downloads of release assets, which can be a useful metric.

**Comment by sjackman** [comment]
Never mind. I found the tarball at https://nixos.org/releases/patchelf/patchelf-0.11/patchelf-0.11.tar.gz. You could if you liked upload this tarball to the GitHub release assets.

**Comment by domenkozar** [comment]
opened https://github.com/NixOS/patchelf/issues/212
