### ISSUE TITLE
CI: upload tarball for tags

### ISSUE THREAD

**Issue by domenkozar** [NixOS/patchelf#212]
Requested in https://github.com/NixOS/patchelf/issues/211

**Comment by sjackman** [comment]
@domenkozar @edolstra Could please include a gzipped tarball in addition to or instead of the bzipped tarball? `patchelf` is the very first package installed on a Homebrew on Linux system, and so `bzip2` may not yet be installed.

**Comment by sjackman** [comment]
The TAR file compressed with `gzip` is 20% larger than with `bzip2`, and compressed with `zopfli` (which can be decompressed with `gzip`) is 14% larger than with `bzip2`.
```console
$ curl -LO https://github.com/NixOS/patchelf/releases/download/0.12/patchelf-0.12.tar.bz2
$ bunzip2 -k patchelf-0.12.tar.bz2
$ zopfli patchelf-0.12.tar
$ wc -c patchelf-0.12.tar.bz2 patchelf-0.12.tar.gz
  165069 patchelf-0.12.tar.bz2
  187570 patchelf-0.12.tar.gz
$ bc -l <<<187570/165069
1.13631269347969636939
```

**Comment by Mic92** [comment]
also includes gzip tarballs.
