### ISSUE TITLE
Feature request: modifing function names in symbol tables.

### ISSUE THREAD

**Issue by twaik** [NixOS/patchelf#213]
Hi. I think it will be useful to create such a feature. It will be useful to create hooks without runtime changes. 
A situation: Android's and GNU/Linux's elf structure is the same. Android's libraries can be loaded by glibc's linker, there is a project called [fake_libc](https://github.com/krnlyng/fake_libc) that allows us to load Android libraries in glibc based program. But Android and GNU/Linux libc implementations are not fully compatible. Libhybris uses runtime hooks. I think we will be able to get rid of hooks using .dynsym and/or .symtab patching.

**Comment by brenoguim** [comment]
Hey @twaik , you might want to give this a try: https://github.com/NixOS/patchelf/pull/459

**Comment by brenoguim** [comment]
#459 was merged, so I think this can be closed
