### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by avikivity** [NixOS/patchelf#232]
**Is your feature request related to a problem? Please describe.**

43a33482b501b0f5ee9da312aabfca3806570cc9 fixes a bug that prevents patchelf from working correctly on aarch64 binaries. However, it is not in any release.

**Describe the solution you'd like**

A new minor or patch release containing 43a33482b501b0f5ee9da312aabfca3806570cc9.

**Describe alternatives you've considered**

Patching my distribution's package (Fedora). However, I think the fix merits a new release.

**Additional context**

NULL

**Comment by delroth** [comment]
@domenkozar how can we get started on this? Is there any kind of QA that patchelf releases usually go through before release? e.g. running nixos tests with a system built using patchelf master?

**Comment by edolstra** [comment]
There is a new release: https://github.com/NixOS/patchelf/releases/tag/0.12
