### ISSUE TITLE
Which release URLs to follow? github or releases.nixos.org?

### ISSUE THREAD

**Issue by rubyFeedback** [NixOS/patchelf#233]
Hey guys,

Latest release is here:

https://github.com/NixOS/patchelf/releases/download/0.12/patchelf-0.12.tar.bz2

But there is also:

https://releases.nixos.org/?prefix=patchelf/

And it does not yet have 0.12

I have no preference either way, but I believe that in the long run it should be decided what to do:

- Offer both github URL releases AND the releases.nixos.org release (but then it should be synced IMO)
- Offer only one and discontinue the other.

Again, I have no real preference here. Perhaps it may be simpler to just have the github variant
and forego the other, but it is not really important.

I mention this mostly because I keep track with ruby of remote packages, and so I had to decide
which release page I would follow. I recently decided that github patchelf seems to be more
active so I am not sure if I will track the other URL anymore, if you guys keep on using
github more. But either way, no matter what you decide, I just wanted to give a bit of feedback
anyway - please do feel free to close this issue at any moment in time to keep the number
of issues low. (patchelf is, by the way, a REALLY good idea. Perhaps it may even be included
into some other upstream package one day like binutils, glibc or gcc, wherever it may fit).

**Comment by edolstra** [comment]
Yeah, I decided to put the new release on github.com since it's more convenient. I noticed we didn't have a link to releases.nixos.org anyway so the releases were pretty undiscoverable.

**Comment by domenkozar** [comment]
See #212

**Comment by haampie** [comment]
So this means releases.nixos.org will not get any updates anymore?

**Comment by edolstra** [comment]
Yes, please use the tarballs on github.
