### ISSUE TITLE
Release archive folder name not deterministic

### ISSUE THREAD

**Issue by ilg-ul** [NixOS/patchelf#247]
**Describe the bug**

I'm trying to integrate patchelf into my build infrastructure, but the resulting folder after unpacking the provided archive has a name that I cannot automatically compute in a script.

**Steps To Reproduce**

Unpack the current `patchelf-0.12.tar.bz2` archive.
The result is a folder like `patchelf-0.12.20200827.8d3a16e`.

**Expected behavior**

A folder with a deterministic name, like `patchelf-0.12`, so I can automatically compute it in a script.

**Comment by edolstra** [comment]
Well, the `.20200827.8d3a16e` *is* deterministically computed from the git revision from which the release is made. But I agree it's a bit ugly that the tarball name doesn't match the top-level directory inside the tarball.

**Comment by ilg-ul** [comment]
What you suggest is that in my scripts I should 

- clone the repo,
- download the archive
- perform a super-smart match of the release tag to a commit 
- from there get the date and short commit id. 

Really?

**Comment by edolstra** [comment]
I suggest unpacking the tarball and doing `cd patchelf-*`. There is no actual bug here.

**Comment by ilg-ul** [comment]
For those who face the same issue, the workaround is to use the GitHub archive, available under the **Source code (tar.gz)** entry, since it expands to a folder with a predictible name.

In my case the `cd patchelf-*` is not realistic, since I have a multi-version build system, and in the folder where I expand the source archives there might be multiple versions of the same package.
