### ISSUE TITLE
patchelf does not find the file

### ISSUE THREAD

**Issue by wellinton-capixaba** [NixOS/patchelf#249]
Hello. I am trying to execute patchelf with:

./patchelf --set-interpreter=/media/34GB/Arquivos-de-Programas-Linux/Glibc-2.17-32bit/lib/ld-linux.so.2  --set-rpath=/media/34GB/Arquivos-de-Programas-Linux/Glibc-2.17-32bit/ /media/34GB/Arquivos-de-Programas-Linux/palemoon/palemoon

and all I receive it is: stat: No such file or directory

The paths seems to be correct ( I used the autocomplete bash function to avoid errors), yet it complains that does not find the file? There might be another reason for this failure in find it than a wrong path?

**Comment by rmNULL** [comment]
Hi @wellinton-capixaba 

You are passing arguments in a manner unsupported by patchelf.
unfortunately,  '=' is not understood by patchelf.

i.e it should be  `--set-rpath RPATH`  not `--set-rpath=`

P.S: by the time i write this, you may have figured that out. If that is the case, please close the issue. Thanks
