### ISSUE TITLE
Add option to remove the SONAME

### ISSUE THREAD

**Issue by Rhialto** [NixOS/patchelf#257]
Sometimes, search paths for libraries cause conflicts between incompatible libraries that have the same SONAME. I once ran into that when I installed multiple versions of g++ which used the same SONAME for the C++ library, but they were incompatible. For some programs, the wrong version was loaded, resulting in mysterious problems.

For cases like this, sometimes it isn't even enough to avoid system-global search paths, and even RPATH in an executable can still not solve this. In that case you want to record the absolute path to a library.

It turns out that current tooling already supports this. I looked in NetBSD's runtime linker and in the binutils compile time linker. You get a full path to a library recorded in the linker output, *if* the library has no SONAME. 

So if you can remove a SONAME from a library, you can use this escape hatch.

I tried in the past to make shim libraries that have no SONAME of themselves, and link to only one other library, with only one directory in the RPATH. That works, but is more complicated.

**Comment by Rhialto** [comment]
There is some mailing list discussion about this, for example starting at http://mail-index.netbsd.org/pkgsrc-users/2020/07/30/msg031864.html and a bunch of "Next by Thread" links.

**Comment by Mic92** [comment]
Also related https://github.com/NixOS/nixpkgs/pull/45105

**Comment by Mic92** [comment]
Have you tried to make soname an absolute path? I think this is what https://github.com/NixOS/nixpkgs/pull/45105/files tries on Linux.

**Comment by Rhialto** [comment]
Ah interesting idea! So if I understand right, the idea is to set the SONAME of a library to an absolute path. Then when that library is referenced (by the compile time linker), the output file will have a DT_NEEDED with that absolute path in it. 

An interesting alternative approach to mine: a library with *no* SONAME will cause the referring file to get an absolute DT_NEEDED (but only if it is specified on the command line that way).

So I tried this on NetBSD (which has at least its own runtime linker, but the compiler and compile time linker are gnu or llvm).
```
#!/bin/sh

cat >hello.c <<\EOF
#include <stdio.h>
int main(int argc, char **argv) {
    printf("Hello, world!\n");
    return 0;
}
EOF

cp /lib/libc.so absolute.so
chmod +w absolute.so

patchelf --set-soname $PWD/absolute.so ./absolute.so

objdump -x absolute.so | grep SONAME

gcc -c hello.c -o hello.o
# Link without the standard libc but with other default objects
CRTEND="-Wl,--as-needed -lgcc_s -Wl,--no-as-needed -lgcc -Wl,--as-needed -lgcc_s -Wl,--no-as-needed -lgcc"
gcc -o hello -nodefaultlibs hello.o ./absolute.so $CRTEND

objdump -x hello | grep NEEDED

./hello
```
which had an interesting result:
```
$ ./doit
  SONAME               /tmp/x/absolute.so
  NEEDED               /tmp/x/absolute.so
/tmp/x/absolute.so: wrong number of segments (3 != 2)
```
where the last line is the result of attempting to run `./hello`.

I'm not sure what that error entails exactly, but I noticed that there is some strange change caused by the `patchelf --set-soname $PWD/absolute.so ./absolute.so` command already:
```
$ ldd /lib/libc.so
/lib/libc.so:
$ ldd ./absolute.so 
ldd: ./absolute.so: invalid ELF class 2; expected 1
```
So it seems that `patchelf` changes more in the file than expected.

**Comment by Rhialto** [comment]
Oh, and if I overwrite the patched library with the original, `hello` runs (so the problem is in the library, not in the executable):
```
$ cp /lib/libc.so ./absolute.so 
overwrite ./absolute.so? y
$ ldd ./hello
./hello:
        /tmp/x/absolute.so => /tmp/x/absolute.so
$ ./hello
Hello, world!
```
All this on NetBSD/amd64 9.2.

**Comment by Rhialto** [comment]
Maybe issue #244 is related?

**Comment by genezx** [comment]
+1. Please add the option to remove SONAME.

There are such use cases and I think it's quite common in production environment.

For example, I have a bunch of different versions of **third-party .so files with all the same SONAME and RPATH in them**, and each of them are not compatible with each other, and then I want to link to a certain version of .so file. So I have to remove the SONAME and RPATH to get a full path linkage to the certain .so file. patchelf has --remove-rpath now, and just lacks an option like --remove-soname.

**Comment by fzakaria** [comment]
Hi!
I think we can close this issue as you can already remove SONAME with the replace functionality.
```bash
❯ patchelf --print-soname libsimple.so
libsimple.so.1.1

❯ patchelf --set-soname "" libsimple.so

❯ patchelf --print-soname libsimple.so
```

Another example:
```
❯ patchelf --set-soname "abc" libsimple.so

❯ readelf -a libsimple.so| grep SONAME
 0x000000000000000e (SONAME)             Library soname: [abc]

❯ readelf -a libsimple.so| grep SONAME
 0x000000000000000e (SONAME)             Library soname: []
```

@Rhialto @genezx @Mic92 should we close?

**Comment by Mic92** [comment]
Sounds good to me.

**Comment by Mic92** [comment]
@Rhialto @genezx I can reopen, if the above does not fit your use case.

**Comment by Rhialto** [comment]
@Mic92 It both does and doesn't, in a way :)

It does, in the sense that with the linker I tried, it seemed to have the same effect as a missing SONAME. The argument I gave to the linker was recorded verbatim in the DT_NEEDED record.

It doesn't, in the sense that this doesn't actually *remove* the record:
```
$ patchelf --set-soname "" ./absolute.so
$ patchelf --debug --print-soname ./absolute.so
DT_SONAME is empty
```
whereas I was expecting that `debug("no DT_SONAME found\n");` would be reached.

**Comment by Mic92** [comment]
Mhm but truncating a string seems to me like the less invasive option because we don't actually need to remove any entries from the dynamic section.

**Comment by cerisier** [comment]
`--set-soname ""`  doesn't effectively remove the DT_SONAME entry, it makes it empty.

This is problematic in my case because I'm linking against a stub library which shouldn't be added as `DT_NEEDED` of a final binary but ends up there because it has a `DT_SONAME`.

Setting `--set-soname ""` still leaves a `DT_SONAME` entry as empty ("") which in turns adds an empty string as entry in `DT_NEEDED`.


```
Dynamic section at offset 0x34dd188 contains 28 entries:
...
 0x0000000000000001 (NEEDED)             Shared library: []
```

**Comment by leleliu008** [comment]
It's very easy to implement `remove-soname` in C:

the idea is just change DT_SONAME entity type to `DT_UNKNOWN 100`:

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <fcntl.h>
#include <unistd.h>

#include <sys/mman.h>
#include <sys/stat.h>

#include <elf.h>

#define DT_UNKNOWN 100

int handle32(unsigned char * elf) {
    Elf32_Ehdr *ehdr = (Elf32_Ehdr *)elf;
    Elf32_Phdr *phdr = (Elf32_Phdr *)(elf + ehdr->e_phoff);
    Elf32_Dyn  *dyn  = NULL;

    for (Elf32_Half i = 0; i < ehdr->e_phnum; i++) {
        if (phdr[i].p_type == PT_DYNAMIC) {
            dyn = (Elf32_Dyn *)(elf + phdr[i].p_offset);
            break;
        }
    }

    if (!dyn) {
        return 1;
    }

    for (size_t i = 0; ; i++) {
        if (dyn[i].d_tag == DT_NULL) {
            return 1;
        }

        if (dyn[i].d_tag == DT_SONAME) {
            dyn[i].d_tag =  DT_UNKNOWN;
            return 0;
        }
    }
}

int handle64(unsigned char * elf) {
    Elf64_Ehdr *ehdr = (Elf64_Ehdr *)elf;
    Elf64_Phdr *phdr = (Elf64_Phdr *)(elf + ehdr->e_phoff);
    Elf64_Dyn  *dyn  = NULL;

    for (Elf64_Half i = 0; i < ehdr->e_phnum; i++) {
        if (phdr[i].p_type == PT_DYNAMIC) {
            dyn = (Elf64_Dyn *)(elf + phdr[i].p_offset);
            break;
        }
    }

    if (!dyn) {
        return 1;
    }

    for (size_t i = 0; ; i++) {
        if (dyn[i].d_tag == DT_NULL) {
            return 1;
        }

        if (dyn[i].d_tag == DT_SONAME) {
            dyn[i].d_tag =  DT_UNKNOWN;
            return 0;
        }
    }
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <FILEPATH>\n", argv[0]);
        return 1;
    }

    int fd = open(argv[1], O_RDWR);

    if (fd < 0) {
        perror(argv[1]);
        return 2;
    }

    struct stat st;

    if (fstat(fd, &st) == -1) {
        perror(argv[1]);
        return 3;
    }

    void * data = mmap(NULL, st.st_size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);

    if (data == MAP_FAILED) {
        perror("mmap");
        close(fd);
        return 4;
    }

    unsigned char * elf = (unsigned char *)data;

    if (memcmp(elf, ELFMAG, SELFMAG) != 0) {
        fprintf(stderr, "Not an ELF file: %s\n", argv[1]);
        munmap(data, st.st_size);
        close(fd);
        return 5;
    }

    int ret;

    switch (elf[EI_CLASS]) {
        case ELFCLASS64: ret = handle64(elf); break;
        case ELFCLASS32: ret = handle32(elf); break;
        default:
            fprintf(stderr, "invalid ELF file: %s\n", argv[1]);
            return 6;
    }

    if (ret == 0) {
        msync(data, st.st_size, MS_SYNC);
    }

    munmap(data, st.st_size);
    close(fd);
    return 0;
}
```

**Comment by leleliu008** [comment]
origin:

```
Dynamic section at offset 0x2e38 contains 21 entries:
  Tag        Type                         Name/Value
 0x000000000000000e (SONAME)             Library soname: [hahahah.so]
 0x000000000000000c (INIT)               0x1000
 0x000000000000000d (FINI)               0x1138
 0x0000000000000019 (INIT_ARRAY)         0x3e28
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x3e30
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2d0
 0x0000000000000005 (STRTAB)             0x3a0
 0x0000000000000006 (SYMTAB)             0x2f8
 0x000000000000000a (STRSZ)              104 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x3fe8
 0x0000000000000002 (PLTRELSZ)           24 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4b0
 0x0000000000000007 (RELA)               0x408
 0x0000000000000008 (RELASZ)             168 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          3
 0x0000000000000000 (NULL)               0x0

```

**Comment by leleliu008** [comment]
changed:

```
Dynamic section at offset 0x2e38 contains 21 entries:
  Tag        Type                         Name/Value
 0x0000000000000064 (<unknown>: 64)      0x5d
 0x000000000000000c (INIT)               0x1000
 0x000000000000000d (FINI)               0x1138
 0x0000000000000019 (INIT_ARRAY)         0x3e28
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x3e30
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2d0
 0x0000000000000005 (STRTAB)             0x3a0
 0x0000000000000006 (SYMTAB)             0x2f8
 0x000000000000000a (STRSZ)              104 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x3fe8
 0x0000000000000002 (PLTRELSZ)           24 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4b0
 0x0000000000000007 (RELA)               0x408
 0x0000000000000008 (RELASZ)             168 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          3
 0x0000000000000000 (NULL)               0x0
```
