### ISSUE TITLE
File execute permission denied after changing the interpereter for a binary

### ISSUE THREAD

**Issue by wide-reciever** [NixOS/patchelf#276]
After changing an interpreter in a binary using the **--set-interpreter**, the file permission get denied from executing for some reason even tho you go and add the execute permission to the file.

**Comment by ans-hub** [comment]
Tried 0.10, 0.11, 0.12 versions. Same problem in fresh installed Ubuntu 18.04.5 LTS

**Comment by khanhncm** [comment]
Hello there. I just have faced this issue. But my issue may not relevant to you. But I hope this help.
I patchelf my python binary. I include
./python3
./python3.8 -> python3 (symlink)

i patchelf both file python3 python3.8. All broken, permission denied on invoke.

Solution:
patchelf only origin file. patchelf only python3. Do not touch its symlink.

Hope it helps. I took me a day to figure it out :(.

**Comment by ans-hub** [comment]
@wide-reciever what OS are you using?

**Comment by khanhncm** [comment]
My OS is Ubuntu 20.04 LTS
I compile python on my local computer running Ubuntu 20.04 LTS, and rsync to my server remote CentOS 7
All works. My issue is I patchelf the symlink also. So magically it dóe not work. Do not touch symlink

**Comment by wide-reciever** [comment]
Linux

**Comment by leesangmin144** [comment]
Hello @wide-reciever, I've got a same issue and solved. In my case, libc & ld files had no 'x'(execute) permission.
Please check your permission whether has 'x'.

**Comment by Mic92** [comment]
It looks like all these permission errors have a different root cause than patchelf itself.
If not please provide a file. However I don't see a case right now where changes to the elf itself would reproduce `permission denied`.

**Comment by ThetaSinner** [comment]
I've got the same error, definitely working against a file and not a symlink. When I pass the `--debug` option to `patchelf` it tells me that the error is happening when trying to write the file back to disk

```
rewriting symbol table section 3
rewriting symbol table section 43
writing myprogram
patchelf: open: Permission denied
```

If I pass `--output myprogram-patched` when I rewrite the interpreter then it succeeds. 

Hopefully, that's a useful workaround for anybody who runs into this error! 

@Mic92 Is there possibly something with the read handle to the file still being held when the write happens?

If it's useful, I'm using v0.15.0 on WSL2/Ubuntu.

**Comment by goyalyashpal** [comment]
> If not please provide a file
> \- _@ Mic92 at https://github.com/NixOS/patchelf/issues/276#issuecomment-900521468_


### System Info:

```console
$ nix --version
nix (Nix) 2.18.5

```

### Additional info

maybe this is caused due to `$NIX_CC` evaluating to `...gcc-wrapper...` and the file is probably compiled with `clang`?


### Minimum Reproducible Example

hi! following `nix-shell` and the given bash script produce a reproducible  MWE.

```bash
nix-shell -p clang aria2
```


```bash
echo
echo "==== ==== ==== ==== ==== ==== ==== ==== ==== ==== ==== ===="
echo "==== ==== ==== ==== ==== ==== ==== ==== ==== ==== ==== ===="
mkdir -p pelf-perm && cd pelf-perm

echo -e "\n==== Downloading File to the "pelf-perm" dir ===="
if test -f "speller50"; then
  echo "./speller50 already exists."
  echo "For downloading fresh sample, please remove it and retry"
else
  aria2c \
    --auto-file-renaming=false \
    --checksum md5='beade36f9993557867c9c0ed981dfb74' \
    "https://cdn.cs50.net/2023/fall/psets/5/speller/speller50"
fi



echo -e "\n\n==== Current interpreter: "
patchelf --print-interpreter ./speller50

echo -e "\n==== Patching File ===="
patchelf --debug --set-interpreter "$NIX_CC/nix-support/dynamic-linker" "./speller50"

echo
chmod -v a+x ./speller50




echo -e "\n==== Running the File ===="
./speller50


echo -e "\ncd out of the "pelf-perm" dir? [Y/n] "
read RESPONSE
RESPONSE=${RESPONSE:0:1}

if [[ ! "${RESPONSE,,}" == "n" ]] then cd ..; fi
```

**Comment by goyalyashpal** [comment]
ping @Mic92
