### ISSUE TITLE
patchelf unable to set interpreter

### ISSUE THREAD

**Issue by caprinux** [NixOS/patchelf#280]
![image](https://user-images.githubusercontent.com/76640319/122152826-6b8fcd00-ce94-11eb-933c-06e09d62ad4e.png)

No idea where else I could ask this but I've compiled this directly from source, off the github. 

Patchelf Version 0.12, Ubuntu 18.04 LTS Desktop.

Does anyone have any idea how to fix this?

**Comment by caprinux** [comment]
Patchelf v0.10 works perfectly fine.

**Comment by domenkozar** [comment]
Could you try v0.13?

**Comment by Mic92** [comment]
Closing because lack of feedback from the author.
