### ISSUE TITLE
v0.13 failing to build on Fedora armv7hl

### ISSUE THREAD

**Issue by jeremysanders** [NixOS/patchelf#294]
Version 0.13 is failing to build in the Fedora automatic update monitoring build for the target armv7hl. It seems to build fine on the other targets. The problem is with one of the self tests (see https://kojipkgs.fedoraproject.org//work/tasks/461/73370461/build.log for more details):

```
gcc  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS    -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -c -o contiguous_note_sections.o contiguous_note_sections.s
contiguous_note_sections.s: Assembler messages:
contiguous_note_sections.s:5: Error: junk at end of line, first unrecognized character is `,'
contiguous_note_sections.s:15: Error: junk at end of line, first unrecognized character is `,'
```

I'm not that familiar with using the assembler but I assume it's something to do with the `@note` following
```
.section ".note.my-section0", "a", @note
```

Looking at the GNU as manual, this seems ok to me, so it's unclear why this should be a problem. I don't have access to an armv7hl machine, so I thought I would file this in case someone knows anything before trying to make a VM.

**Comment by domenkozar** [comment]
Relevant: #283

**Comment by domenkozar** [comment]
cc @mic92

**Comment by Mic92** [comment]
@jeremysanders this is just a test case, should we skip this test on armv7? We still test it on all other platforms so we should not regress on it.

**Comment by Mic92** [comment]
I think for reproducing it would be enough to have a cross compiler for armv7 that comes with an assembler (i.e. pkgsCross.armv7l-hf-multiplatform.stdenv in nix)

**Comment by Mic92** [comment]
```nix
# shell.nix
with import <nixpkgs> {};
pkgsCross.armv7l-hf-multiplatform.stdenv.mkDerivation {
  name = "foo";
}
```

```console
$ nix-shell
nix-shell> echo $AS
armv7l-unknown-linux-gnueabihf-as
nix-shell> $AS -o contiguous_note_sections.o contiguous_note_sections.s
contiguous_note_sections.s: Assembler messages:
contiguous_note_sections.s:5: Error: junk at end of line, first unrecognized character is `,'
contiguous_note_sections.s:15: Error: junk at end of line, first unrecognized character is `,'
```

**Comment by ius** [comment]
Yes, it's reproducible using `armv7l-hf-multiplatform`. The issue is this bit from the manual:

> Note on targets where the @ character is the start of a comment (eg ARM) then another character is used instead. For example the ARM port uses the % character.

The type needs to be `%note` for ARM.

```
-.section ".note.my-section0", "a", @note
+.section ".note.my-section0", "a", %note
```

Which also happens to work for my `x86_64` assembler, for what it's worth. Might need to check whether that extends to other architectures..

**Comment by Mic92** [comment]
Yeah. Also just found it here: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gas/doc/as.texi;h=292c4af2bb60ecbdc1f52c6dedf7dfec3aaa808f;hb=HEAD#l6723

**Comment by Mic92** [comment]
I think autotools has the current target in `@target@`.

**Comment by ius** [comment]
I think it's generally safe to use `%` instead of `@` as long as it doesn't have any special meaning.

[gas/config/obj-elf.c#1233](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gas/config/obj-elf.c;h=42a3851e7722d15bd69f870a40b352ed592186f8;hb=HEAD#l1233):
> else if (c == '@' || c == '%')

Assembles the testcase on `x86_64`, `arm7-multiplaform`, `aarch64-multiplatform`, `powerpc`.
