### ISSUE TITLE
Please release a stable version of patchelf that includes --add-needed

### ISSUE THREAD

**Issue by sjackman** [NixOS/patchelf#31]
Thanks!

**Comment by fsateler** [comment]
Yes please. The getPageSize change is also necessary for builds in ppc64el architecture.

**Comment by darealshinji** [comment]
There have been quite a lot of changes since the last release. It would really be about time for a new release version.

**Comment by sjackman** [comment]
@edolstra Hi, Eelco. Are you around? A new stable release of `patchelf` would be helpful.

**Comment by edolstra** [comment]
Yes, I'll try to make a new release in the next few days.

**Comment by sjackman** [comment]
Wonderful! Thanks, Eelco.

**Comment by edolstra** [comment]
New release: http://nixos.org/releases/patchelf/patchelf-0.9/

**Comment by sjackman** [comment]
Thanks!
