### ISSUE TITLE
Add zsh completion support

### ISSUE THREAD

**Issue by Y7n05h** [NixOS/patchelf#310]
I found that patchelf lacks shell completion support.
I am willing to write zsh completion scripts for patchelf. If it’s acceptable, I’m happy to send a Pull Request

**Comment by Freed-Wu** [comment]
Any progress about this issue?

**Comment by Y7n05h** [comment]
> Any progress about this issue?

I am so sorry.  I didn't continue to work on it.  I haven't been using patchelf for a long time.
