### ISSUE TITLE
Add a .tar.gz archive with configure script

### ISSUE THREAD

**Issue by haampie** [NixOS/patchelf#320]
**Is your feature request related to a problem? Please describe.**
`patchelf` is used in the Spack package manager for bootstrapping its binary dependencies. During bootstrapping it's nice to have very few system dependencies, and patchelf implicitly creates a dependency on bzip2, because it is released as a bzip2 archive only as of version 0.12.

**Describe the solution you'd like**
It'd be great if we additionally could get release tarballs with generated configure file compressed with gzip (so .tar.gz), since gzip is usually provided by the distro, whereas bzip2 might require installation first. In particular it would be nice to have an additional upload of patchelf 0.13 as tar.gz too.

**Comment by Mic92** [comment]
Github has both: https://github.com/NixOS/patchelf/releases/tag/0.13.1
