### ISSUE TITLE
man page on `--set-rpath` does not reflect the changes in DT_RUNPATH

### ISSUE THREAD

**Issue by stephenmsachs** [NixOS/patchelf#328]
The option mentioned in the man page sections on manipulating RPATH actually work on RUNPATH. Please disregard this bug if this is common notation, but I would expect the man page to say "Change the RUNPATH of the executable ..."

```
.IP "--set-rpath RPATH"
Change the RPATH of the executable or library to RPATH.
```
I only found out that `--set-rpath` sets DT_RUNPATH instead of RPATH after reading through the `--force-rpath` section.

**Comment by Mic92** [comment]
Thanks for your finding. Could you open a PR?

**Comment by stephenmsachs** [comment]
I opened https://github.com/NixOS/patchelf/pull/331

**Comment by stephenmsachs** [comment]
https://github.com/NixOS/patchelf/pull/331 is merged. This can be closed.
