### ISSUE TITLE
libc/glibc version dependencies hell - help needed

### ISSUE THREAD

**Issue by psammarco** [NixOS/patchelf#332]
Hello, this is more of  a help request rather than a bug submission.

I manage an HPC that makes available a huge library of scientific software, each served as standalone application through the use of _module(1)_.

I am trying to overcome an issue related to glibc/libc discrepancy versions with a software called shapeit4. The software in question was built on a different host and with a different version of glibc than the one provided by the HPC.

The shapeit4 dependencies libraries were copied from the building host to the HPC along with the binary software itself.

I have then patched the ld-linux-x86-64.so.2 library using patcher as shown below, however it is now throwing a new glibc version error.

**Patching:**
```
003:/resources/tools/apps/software/bio/shapeit4/4.2.2/bin$ ~/patchelf-0.13.20210805.a949ff2/src/patchelf --set-interpreter /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/ld-linux-x86-64.so.2 --set-rpath /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/ shapeit4.2
```

**New error post patching:**
```
003:/resources/tools/apps/software/bio/shapeit4/4.2.2/bin$ shapeit4.2
shapeit4.2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by shapeit4.2)
shapeit4.2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by shapeit4.2)
shapeit4.2: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/libboost_iostreams.so.1.76.0)
shapeit4.2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/libboost_iostreams.so.1.76.0)
shapeit4.2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/libboost_program_options.so.1.76.0)
shapeit4.2: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/libboost_program_options.so.1.76.0)
shapeit4.2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /resources/tools/apps/software/bio/shapeit4/4.2.2/lib/libboost_program_options.so.1.76.0)
003:/resources/tools/apps/software/bio/shapeit4/4.2.2/bin$
```

**Here is the content of the shapeit4 dependencies:**
```
003:~$ ls /resources/tools/apps/software/bio/shapeit4/4.2.2/lib
ld-2.33.so            libboost_iostreams.so         libboost_program_options.so         libcrypto.so.1.1  libhts.so       libhts.so.3  libssl.so.1.1
ld-linux-x86-64.so.2  libboost_iostreams.so.1.76.0  libboost_program_options.so.1.76.0  libc.so.6         libhts.so.1.13  libm.so.6    libstdc++.so.6
003:~$
```

Do you have any idea as to how this libc/glibc version dependencies hell could be resolved? 

**`patchelf --version` output**

```
n003:~/patchelf-0.13.20210805.a949ff2$ src/patchelf --version
patchelf 0.13.20210805.a949ff2
003:~/patchelf-0.13.20210805.a949ff2$
```
Any help will be much appreciated. 

Regards,
Pietro

**Comment by Mic92** [comment]
I am closing this issue, since we use the bug tracker for open issues in patchelf, but this does not mean we can still address the question in this thread.

To me it seems ld you build is still configured to lookup it's libc from `/lib64`. To solve this, I would try to compile & install an old glibc version using `/resources/tools/apps/software/bio/shapeit4/4.2.2/` as an installation prefix in the configure script.
Than you should be able to follow your patchelf procedure.

Beeing a nix maintainer I would probably use `autoPatchelfHook` from nixpkgs and compile an old glibc version but this is a different story.
