### ISSUE TITLE
Another release?

### ISSUE THREAD

**Issue by haampie** [NixOS/patchelf#334]
Once more I'm hitting a bug only to find out it's fixed for a while on `master`, it's just not released. This one:

https://github.com/NixOS/patchelf/pull/319

Can you please make releases regularly? And maybe even consider backports? Some distro's provide terribly old versions of patchelf, but even distro's that tend to ship new versions don't get the latest bug fixes, because patchelf doesn't make releases very regularly.

**Comment by haampie** [comment]
Regarding backports, it'd be nice to have 0.17.1 with bugfixes, but without https://github.com/NixOS/patchelf/pull/323 which has bumped the required cmake version to c++17 :( that complicates installing patchelf from sources on old distros

**Comment by domenkozar** [comment]
cc @Mic92

**Comment by Mic92** [comment]
I asked @edolstra if we can make a new release. I would accept a bugfix release if you @haampie could prepare the backport branch with changelogs.

**Comment by haampie** [comment]
https://github.com/haampie/patchelf/tree/release-0.13

**Comment by Mic92** [comment]
Fixed.
