### ISSUE TITLE
New 0.14.1 release seems to have strange directory

### ISSUE THREAD

**Issue by jeremysanders** [NixOS/patchelf#345]
I'm trying to update the Fedora distribution package for patchelf. If I untar the .tar.gz or .tar.bz2 in the download area, the source has a strangely named subdirectory.

```
$ tar tf patchelf-0.14.1.tar.gz 
patchelf-0.14.1.19700101.dirty/
patchelf-0.14.1.19700101.dirty/aclocal.m4
patchelf-0.14.1.19700101.dirty/configure
patchelf-0.14.1.19700101.dirty/build-aux/
...
```

Is this intended? It makes it difficult to make a package.

**Comment by Mic92** [comment]
see https://github.com/NixOS/patchelf/pull/346

**Comment by jeremysanders** [comment]
Thanks very much!
