### ISSUE TITLE
Avoiding crash for older compilers, or atleast adding checks.

### ISSUE THREAD

**Issue by mohammad-akhlaghi** [NixOS/patchelf#377]
When older C++ compilers are used, more recent versions of patchelf will crash immediately after the configure step. 

This happened for me when building patchelf 0.13 on a system with GCC 4.4.5 (from 2010). The error was in the make phase (after `./configure`):

```
cc1plus: error: unrecognized command line option "-std=c++11"
```

It is expected that, when C++11 features (or any other feature!) is required,  the necessary check be done in the configure phase, and let the user know in a more elegant and clear way. Not in the `make` phase.

More generally it would be great if you can separate the parts that depend of C++11 (or more recent standards) and add wrappers for them, so systems with older compilers can also benefit from patchelf (especially given the very low-level nature of patchelf: making it necessary when bootstrapping new software on older systems).

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/patchelf/pull/383
