### ISSUE TITLE
configure check for -std=c++17 insufficient

### ISSUE THREAD

**Issue by mkoeppe** [NixOS/patchelf#393]
**Describe the bug**

debian-stretch has gcc 6.3.0-18+deb9u1, which accepts the flag `-std=c++17` but does not have `<optional>`

https://trac.sagemath.org/ticket/34081#comment:34

**Comment by Mic92** [comment]
Where do they put `<optional>` on debian?

**Comment by Mic92** [comment]
Also is debian 9 not end-of-life anyway?

**Comment by mkoeppe** [comment]
It's not Debian-specific.

I got here on the route SciPy -> https://github.com/FFY00/meson-python -> patchelf, and SciPy purports to support GCC 6.3 https://docs.scipy.org/doc/scipy/dev/toolchain.html#c-language-standards @rgommers

**Comment by rgommers** [comment]
We actually just dropped that @mkoeppe. The link above is for the stable release, which does still support GCC 6.3 but also does _not_ support C++17. In `main` we merged a PR that specifies we can start using C++17 but GCC 8 is the minimum: http://scipy.github.io/devdocs/dev/toolchain.html#compilers

**Comment by mkoeppe** [comment]
@rgommers, thanks for the info. Yes, it's affecting the build of stable scipy (1.9.x). I ran into it in https://trac.sagemath.org/ticket/34081

@Mic92 I don't need a solution here. We are just using patchelf 0.13.1 until we can bump our compiler requirements. I just wanted you to be aware that if you attempt to check C++17 support of the compiler, checking whether compiler accepts the `-std=c++17` is not enough. You may want to use something like https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_17.html
