### ISSUE TITLE
Test failures on ia64

### ISSUE THREAD

**Issue by matoro** [NixOS/patchelf#396]
**Describe the bug**

Hi, I would like to get patchelf running on ia64.  Unfortunately there are currently a handful of test failures.  I have collected this information here with the hope somebody could take a crack at it.

*I have hardware available to test!  If hardware access is needed, please let me know and I can get you a shell account!*

**Steps To Reproduce**

Tried a number of different environments.  I'll only list the failed tests here to make comparison easier.

*Gentoo version 0.15.0, via portage*:  9 failures
```
FAIL: no-rpath.sh
FAIL: set-rpath.sh
FAIL: add-rpath.sh
FAIL: set-rpath-library.sh
FAIL: set-interpreter-long.sh
FAIL: output-flag.sh
FAIL: grow-file.sh
FAIL: replace-add-needed.sh
FAIL: big-dynstr.sh
```
Log:  https://bugs.gentoo.org/attachment.cgi?id=798115

*Gentoo version 0.15.0, via portage, with optimization disabled (`-O0 -g`)*:  4 failures
```
FAIL: no-rpath.sh
FAIL: set-rpath-library.sh
FAIL: big-dynstr.sh
FAIL: replace-add-needed.sh
```

*Git master checkout, default flags*:  8 failures
```
FAIL: set-interpreter-long.sh
FAIL: set-rpath.sh
FAIL: add-rpath.sh
FAIL: no-rpath.sh
FAIL: set-rpath-library.sh
FAIL: output-flag.sh
FAIL: grow-file.sh
FAIL: replace-add-needed.sh
```

I have had quite a few packages where I've had to disable particular compiler optimizations for ia64, even at "safe" levels like -O2, so I would use -O0 as the baseline.

According to Debian, 0.11 is the last working version:  https://buildd.debian.org/status/logs.php?pkg=patchelf&arch=ia64

I tried checking out the 0.11 tag from git, and got only one failure:
```
FAIL: set-rpath-library.sh
```
but it's unclear if this is because newer versions added additional tests or not.

**`patchelf --version` output**

```
patchelf 0.15.0
```

**Additional context**

Again, I have hardware available for anyone who needs it to take a look at this!  Just let me know if you are interested!

Downstream tracking bug:  https://bugs.gentoo.org/863845

**Comment by Mic92** [comment]
As a starter can you give us `tests/test-suite.log`. This file will contain the full error messages.

**Comment by matoro** [comment]
> As a starter can you give us `tests/test-suite.log`. This file will contain the full error messages.

Attached it to the Gentoo bug - thought I attached it here also, guess not.  It's at https://bugs.gentoo.org/attachment.cgi?id=798115

**Comment by Mic92** [comment]
Ok. Thanks. I have now more time again to look at this. I think would need hardware access to see what is going on.

**Comment by matoro** [comment]
> Ok. Thanks. I have now more time again to look at this. I think would need hardware access to see what is going on.

Absolutely - I've provisioned you an account with your ssh key at:  mic92 <at> ia64dev <dot> matoro <dot> tk.  It's accessible over IPv6 only - let me know if you are able to log in!

**Comment by Mic92** [comment]
@matoro thanks. that works.

**Comment by Mic92** [comment]
I had 11 failures until I added support for its page size: https://github.com/NixOS/patchelf/pull/428
Now it's 8.

**Comment by Mic92** [comment]
Ah. actually I messed up a test program. Only 2 failures left ;)

**Comment by Mic92** [comment]
One test failure left after: https://github.com/NixOS/patchelf/pull/430

**Comment by matoro** [comment]
> One test failure left after: #430

Could you document what is the last remaining failure and what the error is?

**Comment by thesamesam** [comment]
ping

**Comment by Mic92** [comment]
I do no longer have access to the said itanium64 machine as my access got revoked.

**Comment by matoro** [comment]
> I do no longer have access to the said itanium64 machine as my access got revoked. I don't recall what the issues where.

Hi Jörg, sorry about that - forgot to update some firewall rules after making an infrastructure change.  It should be on a different IP now, but still accessible.  Can you try again please?

**Comment by Mic92** [comment]
> Hi Jörg, sorry about that - forgot to update some firewall rules after making an infrastructure change. It should be on a different IP now, but still accessible. Can you try again please?

Thanks. Works again.

**Comment by Mic92** [comment]
PASS: plain-fail.sh
PASS: plain-run.sh
PASS: shrink-rpath.sh
PASS: set-interpreter-short.sh
PASS: set-interpreter-long.sh
PASS: set-rpath.sh
PASS: add-rpath.sh
PASS: no-rpath.sh
PASS: big-dynstr.sh
PASS: set-rpath-library.sh
PASS: soname.sh
PASS: shrink-rpath-with-allowed-prefixes.sh
PASS: set-rpath-rel-map.sh
PASS: force-rpath.sh
PASS: plain-needed.sh
PASS: output-flag.sh
PASS: too-many-strtab.sh
PASS: no-rpath-pie-powerpc.sh
PASS: build-id.sh
PASS: invalid-elf.sh
PASS: endianness.sh
PASS: contiguous-note-sections.sh
PASS: no-gnu-hash.sh
PASS: change-abi.sh
PASS: grow-file.sh
PASS: no-dynamic-section.sh
PASS: args-from-file.sh
PASS: basic-flags.sh
PASS: set-empty-rpath.sh
PASS: phdr-corruption.sh
PASS: replace-needed.sh
PASS: replace-add-needed.sh
PASS: add-debug-tag.sh
PASS: repeated-updates.sh
PASS: empty-note.sh
PASS: print-execstack.sh
PASS: modify-execstack.sh
PASS: rename-dynamic-symbols.sh
PASS: overlapping-segments-after-rounding.sh
PASS: no-rpath-amd64.sh
PASS: no-rpath-armel.sh
PASS: no-rpath-armhf.sh
PASS: no-rpath-hurd-i386.sh
PASS: no-rpath-i386.sh
PASS: no-rpath-ia64.sh
PASS: no-rpath-kfreebsd-amd64.sh
PASS: no-rpath-kfreebsd-i386.sh
PASS: no-rpath-mips.sh
PASS: no-rpath-mipsel.sh
PASS: no-rpath-powerpc.sh
PASS: no-rpath-s390.sh
PASS: no-rpath-sh4.sh
PASS: no-rpath-sparc.sh
============================================================================
Testsuite summary for patchelf 0.17.2
============================================================================
# TOTAL: 54
# PASS:  54
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/home/mic92/patchelf/tests'
make[2]: Leaving directory '/home/mic92/patchelf/tests'
make[1]: Leaving directory '/home/mic92/patchelf/tests'
make[1]: Entering directory '/home/mic92/patchelf'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/home/mic92/patchelf'
mic92@matoro-ia64dev ~/patchelf $

Looks like in master all current tests are working...

**Comment by matoro** [comment]
Confirming everything looks good on 0.17.2 as well.  Thank you!
