### ISSUE TITLE
patchelf: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections

### ISSUE THREAD

**Issue by ferologics** [NixOS/patchelf#400]
### Describe the bug
We're trying to `--replace-needed` on a `.so` library for a new name.

### Steps To Reproduce
1. download & unzip [libswiftCore.so.zip](https://github.com/NixOS/patchelf/files/9397254/libswiftCore.so.zip)
3. run `patchelf --replace-needed libc++_shared.so libc++_shared_24.so libswiftCore.so`
4. observe the error

### Expected behavior
The command should succeed.

### Environment
patchelf 0.15.0 / M1 Pro / mbp 16" 2021 / macOS Monterey 12.5.1 (21G83)

### Additional context
Related to https://github.com/buttaface/swift-android-sdk/issues/65

**Comment by Survive2** [comment]
this problem occurs to me,too!Do you have any ideas to how to fix it?

**Comment by ferologics** [comment]
@Survive2 you should run this from ubuntu (the error only occurs on macOS)
