### ISSUE TITLE
building for Slackware makinng big file size 2.5Mb instead of 150kb , need to be stripped ?

### ISSUE THREAD

**Issue by masterwishx** [NixOS/patchelf#405]
not should be a bug but
when building in slackware i have big file size 2.5Mb instead of 150Kb , also patchelf-0.15.0-x86_64-1.txz avalible for slackware in pkgs and its have small 150kb unpacked ....

should i use some sort of strip but dont know how to use it ...:)

**Comment by masterwishx** [comment]
sorry , sudo strip -s patchelf is making the the file is 150kb , i hope i can use it ?

**Comment by Mic92** [comment]
Yes, removing debug symbols with strip is fine for release builds.
