### ISSUE TITLE
Suggestion: use getpagesize()

### ISSUE THREAD

**Issue by Sierra-Sam** [NixOS/patchelf#41]
patchelf.cc has hard-coded values for pageSize.
I believe it would be more portable if PageSize were
discovered using the getpagesize() function.

Also, when I do code that involves size of any kind,
including page size, I use type, size_t.  But, in this
case no one would care.  Besides, getpagesize()
returns an int, but that is only because it is old.

**Comment by darealshinji** [comment]
I guess this can be closed because of https://github.com/NixOS/patchelf/commit/35ecfa7b62c1737e7d1edfc5c9ead2ddf692bd08

**Comment by fsateler** [comment]
Even more now that #73 has been merged.
