### ISSUE TITLE
Version 0.16.0 not bumped

### ISSUE THREAD

**Issue by ZhongRuoyu** [NixOS/patchelf#422]
**Describe the bug**

Version 0.16.0 has been released, but it seems that the [`version`](https://github.com/NixOS/patchelf/blob/0.16.0/version) file was not bumped. As a result the version string seen in the distributed tarballs and binaries (the ones on the [release page](https://github.com/NixOS/patchelf/releases/tag/0.16.0)) is still 0.15.0.

**Steps To Reproduce**

*Not applicable*

**Expected behavior**

The version string in `patchelf --version` output, the generated `configure` script, etc. should reflect the version bump.

**`patchelf --version` output**

*Not applicable*

**Additional context**

**Comment by Mic92** [comment]
Addressed in https://github.com/NixOS/patchelf/releases/tag/0.16.1

**Comment by ZhongRuoyu** [comment]
Thanks!
