### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by VanHoevenTR** [NixOS/patchelf#424]
Is it possible to port this tool to Windows? I needed it specifically for Android .so files

**Comment by Mic92** [comment]
In theory yes, but no one has tested it on windows I strongly suspect.

I think mainly you would need to figure out on how to get missing headers for elf data structures. Maybe projects like mingw would work...

**Comment by Mic92** [comment]
Nix is not required at all. All you need is a c++17 enabled compiler and an environment to build the configure script (that comes from autotools).

**Comment by Mic92** [comment]
If CI goes green than the next release will have patchelf binaries for windows: https://github.com/NixOS/patchelf/pull/438/files

**Comment by Mic92** [comment]
works: https://github.com/NixOS/patchelf/actions/runs/3406053386/jobs/5664657215#step:5:5

**Comment by Mic92** [comment]
Next release will be after I had a look at mips.
