### ISSUE TITLE
Segmentation fault on aarch64 when using `--add-needed` parameter

### ISSUE THREAD

**Issue by Redbeanw44602** [NixOS/patchelf#425]
**Describe the bug**

I'm trying to make an ELF file to load my shared library, and when I declare dependencies using the command, I get a segmentation fault error on startup.

**Steps To Reproduce**

1. patchelf --add-needed the-so-file.so target.elf
2. chmod +x target.elf && ./target.elf
3. `Segmentation fault`

I'm pretty sure it's not an issue with the shared library as it worked fine when I used dynamic injection earlier.

**Expected behavior**

The program starts normally and loads the extra shared library.

**`patchelf --version` output**

patchelf 0.16.1

**Additional context**

The system environment is ARM64 (I'm not sure if patchelf is for ARM64?)

Please help me, any help is greatly appreciated!

**Comment by Mic92** [comment]
Sorry without steps to reproduce this (i.e. source code that we can compile), we cannot help you here.
If you have something that can be reproduced in an hermetic environment i.e. docker
I can have a look.

**Comment by WangYneos** [comment]
# Steps to reproduce the issue: 
> you will need a Android Phone(aarch64) with Termux App(download from Github)

## first: prepare a simple and clean executable and compile it with clang toolchain in termux or NDK toolchain
```
apt install clang
vim a.c
# create a simple "helloword" application
clang a.c
```
execute it and you will be able to see the application is working correctly.

## second: prepare a simple library
```
#include <stdio.h>
static void lib_entry() __attribute__((constructor));
void lib_entry() {
    printf("injected!");
}
```
compile it into a shared lib using `clang -shared -o libxxx.so libxxx.c`, make sure the lib is in system library path

## third: use patchelf to add a simple library
download [Release 0.17.0 aarch64](https://github.com/NixOS/patchelf/releases/download/0.17.0/patchelf-0.17.0-aarch64.tar.gz) 
patch our executable using `./patchelf --add-needed libxxx.so a.out`

after these steps, try to execute the executable again and you will find it terminated by system signal SIGSEGV(Address boundary error) immediately

**Comment by Mic92** [comment]
Ok. Closing the issue than.
