### ISSUE TITLE
`make check` fails on AlmaLinux 8 on arm8 CPU

### ISSUE THREAD

**Issue by bigcat88** [NixOS/patchelf#429]
On arm8 two tests fails.

**FAIL: replace-add-needed.sh**
**FAIL: set-interpreter-long.sh**

**Steps To Reproduce**
```
FROM almalinux:8.6

RUN \
  dnf update -y && \
  dnf install -y \
    git \
    cmake \
    autoconf \
    automake \
    gcc \
    gcc-c++ && \
  echo "**** Installing Patchelf ****" && \
  git clone https://github.com/NixOS/patchelf.git && \
  cd patchelf && \
  ./bootstrap.sh && ./configure && make && make check && make install
```

**Expected behavior**

To pass tests... python's `auditwheel` produce invalid binaries on that OS.

**`patchelf --version` output**
0.16.1
0.17.0-alpha

**Additional context**

patchelf was tested on amd64 on the same OS - it was fine and works fine.
We need that on AlmaLinux 8 to work, cause this OS is officially used to build python libraries.

**Comment by Mic92** [comment]
We would also need `tests/replace-add-needed.sh.log` and `tests/set-interpreter-long.sh.log` produced by these tests to see what is going wrong.

**Comment by bigcat88** [comment]
[patchelf 0.17.0-alpha: tests/test-suite.log](https://gist.github.com/bigcat88/4fe154c7b34e9340a90df5d45767c666)

Look like there is no much info...

**Comment by Redbeanw44602** [comment]
I think this is related to #425

**Comment by bigcat88** [comment]
Looks like my problem is duplicate of https://github.com/NixOS/patchelf/issues/426

**Comment by Mic92** [comment]
The `add-debug-tag.sh` is due a binutils bug that I have worked around in https://github.com/NixOS/patchelf/pull/435

**Comment by Mic92** [comment]
I cannot reproduce any of the test failures anymore in almalinux on aarch64.

This is what I run:

```
[root@07bfd7de4c43 src]# uname -a
Linux 07bfd7de4c43 5.10.150 #1-NixOS SMP Wed Oct 26 11:25:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
> docker run -v$(pwd):/src --rm -ti arm64v8/almalinux   
> dnf install -y autoconf automake gcc gcc-c++
> ./bootstrap.sh 
> ./configure
> make
> make check
>  cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.6 (Sky Tiger)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.6"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Comment by bigcat88** [comment]
`Linux buildkitsandbox 5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
AlmaLinux the same version that in your logs - tests failed...
maybe it is some GitHub error in emulator?
Looks like it is not easily reproducible.

**Comment by Mic92** [comment]
I tested this on real hardware and using qemu-user on x86_64 emulation.

**Comment by bigcat88** [comment]
I can create a test repo with one action file and dockerfile that reproduce what I got, or can close an issue. I do not understand how we got different results and what cause this.

**Comment by thesamesam** [comment]
If you have some way of reproducing it easily, then of course it'd be great to share it.

**Comment by bigcat88** [comment]
https://github.com/bigcat88/test_patchelf

**Comment by bigcat88** [comment]
I am closing this, cause on `quay.io/pypa/manylinux_2_28_x86_64` docker image(os is the same) it is works...
