### ISSUE TITLE
Syntax error for AX_CXX_COMPILE_STDCXX(17, noext, )

### ISSUE THREAD

**Issue by WNZhao1988** [NixOS/patchelf#448]
**Describe the bug**
when I run ./configure, I encoutered this error:

![image](https://user-images.githubusercontent.com/76765350/207005594-3d6e3ecf-20b9-4afd-92f2-a01176c7a4c8.png)

Do you know why this happened?
 
Thank you

**Comment by Mic92** [comment]
Look like you have run autotools in a way it that it has not replaced the AX_CXX_COMPILE_STDCXX macro correctly. The macro is provided by patchelf: https://github.com/NixOS/patchelf/blob/master/m4/ax_cxx_compile_stdcxx.m4

Running `autoconf-2.71` does generate a correct `./configure` script here:

```
$ autoreconf --verbose --install --force --warnings=all
$  grep AX_CXX_COMPILE_STDCXX ./configure
```

only configure.ac should have this string:

```
$ grep AX_CXX_COMPILE_STDCXX ./configure.ac
$ AX_CXX_COMPILE_STDCXX([17], [noext], [])
```

You can download https://github.com/NixOS/patchelf/releases/download/0.17.0/patchelf-0.17.0.tar.bz2 for a an archive where the ./configure script is already pregenerated.

**Comment by WNZhao1988** [comment]
@Mic92 Thank you for your help!

**Comment by Mic92** [comment]
I assume this was solved?

**Comment by AllanSchrum** [comment]
I found that my automake was too old (had 1.11.1 installed on an old machine). Using autoconf 2.71 and automake 1.16.5 it all worked correctly.
