### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dendi777** [NixOS/patchelf#450]
There is such an error when trying to install patchelf will you help me?
--------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying "Unix Makefiles" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 12.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 12.2.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Unix Makefiles" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e/_skbuild/linux-armv7l-3.10/cmake-build
        Command:
          cmake /tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e/_skbuild/linux-armv7l-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-leolgmf3/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/arm-linux-gnueabihf/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is GNU 12.2.0
      -- The CXX compiler identification is GNU 12.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      CMake Warning:
        Manually-specified variables were not used by the project:

          PYTHON_EXECUTABLE
          PYTHON_INCLUDE_DIR
          PYTHON_LIBRARY
          PYTHON_VERSION_STRING
          Python3_EXECUTABLE
          Python3_FIND_REGISTRY
          Python3_INCLUDE_DIR
          Python3_ROOT_DIR
          Python_EXECUTABLE
          Python_FIND_REGISTRY
          Python_INCLUDE_DIR
          Python_ROOT_DIR
          SKBUILD

      -- Build files have been written to: /tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e/_skbuild/linux-armv7l-3.10/cmake-build
      [ 11%] Creating directories for 'build_patchelf'
      [ 22%] No download step for 'build_patchelf'
      [ 33%] No update step for 'build_patchelf'
      [ 44%] Performing patch step for 'build_patchelf'
      ./bootstrap.sh: 2: autoreconf: not found
      gmake[2]: *** [CMakeFiles/build_patchelf.dir/build.make:113: build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch] Error 127
      gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/build_patchelf.dir/all] Error 2
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "/tmp/pip-build-env-leolgmf3/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 640, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-leolgmf3/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 684, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-leolgmf3/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 715, in make_impl
          raise SKBuildError(

      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e
        Working directory:
          /tmp/pip-install-00y3nixx/patchelf_1aaaee9b962d4db185c4cb543b81aa5e/_skbuild/linux-armv7l-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for patchelf
Failed to build patchelf
ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects

**Comment by marcelotduarte** [comment]
This error is caused by `pip install patchelf` as it does not support armv7l.
https://github.com/mayeut/patchelf-pypi

**Comment by Mic92** [comment]
Please report to patchelf-pypi directly instead. We are not maintaining this particular package that seems to use cmake under the hood.

**Comment by TheFaheem** [comment]
Same issue for me too. Can Somebody Help me.
