### ISSUE TITLE
After three times --remove-needed, it will cause "Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!"

### ISSUE THREAD

**Issue by ANaCiSkE** [NixOS/patchelf#455]
**Describe the bug**

After three times --remove-needed, 
it will cause "Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!"

**Steps To Reproduce**

patchelf --remove-needed liba.so libtarget.so
ldd libtarget.so // fine

patchelf --remove-needed libb.so libtarget.so
ldd libtarget.so // fine

patchelf --remove-needed libc.so libtarget.so
ldd libtarget.so // broken
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

**Expected behavior**

**`patchelf --version` output**
patchelf 0.17.2

**Additional context**

**Comment by ANaCiSkE** [comment]
It maybe cannot be reproduced in every libarary.
Please feel free to close this issue if you think that's rare cases.

**Comment by Mic92** [comment]
I don't think we are using this flag a lot in the nixpkgs. It's more often used by people dealing with proprietary legacy software, so I assume it still has a few edge cases...

**Comment by ANaCiSkE** [comment]
thanks a lot

**Comment by wrighton** [comment]
I bumped into this issue. One removal was fine. Two created the error.
