### ISSUE TITLE
Tests fail on PIC executables: maximum file size exceeded

### ISSUE THREAD

**Issue by ppisar** [NixOS/patchelf#47]
Fedora Linux distribution started to build all executables as position-independent code. 

patchelf fails selftest on such executables (see the 'maximum file size exceeded'):

```
$  ../src/patchelf --set-interpreter /oops scratch/set-interpreter-short/simple
warning: working around a Linux kernel bug by creating a hole of 18870272 bytes in ‘scratch/set-interpreter-short/simple’
maximum file size exceeded
```

The reproducer is to call configure as:

```
$ ./configure CFLAGS='-O0 -fPIE' LDFLAGS='-specs=/usr/lib/rpm/redhat/redhat-hardened-ld' CXXFLAGS='-O0 -fPIE'
```

The /usr/lib/rpm/redhat/redhat-hardened-ld contains:

```
*self_spec:
+ %{!shared:%{!r:-pie}}

*link:
+ -z now
```

Alternatively you can replace LDFLAGS with '-z now' and add '-pie' to LDFLAGS_local variable in tests/Makefile.am (and run autoreconf before ./configure).

Complete test suite results are:

```
PASS: plain-fail.sh
PASS: plain-run.sh
PASS: shrink-rpath.sh
FAIL: set-interpreter-short.sh
FAIL: set-interpreter-long.sh
FAIL: set-rpath.sh
PASS: no-rpath.sh
FAIL: big-dynstr.sh
FAIL: set-rpath-library.sh
PASS: soname.sh
PASS: no-rpath-amd64.sh
PASS: no-rpath-armel.sh
PASS: no-rpath-armhf.sh
PASS: no-rpath-hurd-i386.sh
PASS: no-rpath-i386.sh
XFAIL: no-rpath-ia64.sh
PASS: no-rpath-kfreebsd-amd64.sh
PASS: no-rpath-kfreebsd-i386.sh
PASS: no-rpath-mips.sh
PASS: no-rpath-mipsel.sh
PASS: no-rpath-powerpc.sh
PASS: no-rpath-s390.sh
PASS: no-rpath-sh4.sh
PASS: no-rpath-sparc.sh
```

**Comment by ppisar** [comment]
Here <https://kojipkgs.fedoraproject.org//work/tasks/3043/10123043/build.log> you can seen comple build log. It happens on amd64 as well on i686.

**Comment by ppisar** [comment]
The issue is that maxSize is set to fileSize + 8 MB, the output buffer is allocated to the maxSize, then a hole is detected. But the hole is bigger than 8 MB, thus the growFile() aborts.

Either the 8 MB constant should be raised to bigger arbitrary constant, or the output buffer and the maxSize should be enlarged by the hole, or the detected hole is bogus in case of PIE executables.

**Comment by ppisar** [comment]
I confirm it solves the issue. Thank you.

**Comment by dongli** [comment]
I cloned the latest commit, and build on a Ubuntu 14.04. The test failed as:
```
========================================
   patchelf 0.8: tests/test-suite.log
========================================

# TOTAL: 24
# PASS:  23
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: no-rpath.sh
=================

Kernel page size is 4096 bytes
FAIL no-rpath.sh (exit status: 1)
```
