### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libxxx.so"

### ISSUE THREAD

**Issue by peterRedtea** [NixOS/patchelf#480]
**Describe the bug**
Run the command with a so library named **libtest.so** for android arm32 device:
```
patchelf --add-needed libdep.so libtest.so
```
then put the so library into the android project, and build a app to run in the **Android 5.1 armeabi-v7a** device**, throw a exception:
```
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libtest.so" (built with --hash-style=gnu?)
```
**Expected behavior**

Work fine without exception in Android5.1 device.

**`patchelf --version` output**
0.16.1 && 0.17.2
The above two versions have this problem.

**Comment by brenoguim** [comment]
Can you attach the library before and after patchelf, together with the patchelf command you executed?
If not, can you post the result of `readelf -a -W yourlib.so` before and after patchelf?
That really helps debuggigng. Thanks!

**Comment by peterRedtea** [comment]
> Can you attach the library before and after patchelf, together with the patchelf command you executed? If not, can you post the result of `readelf -a -W yourlib.so` before and after patchelf? That really helps debuggigng. Thanks!

I'm so sorry, because the library is private, I cannot provide the content by the command.

**Comment by Mic92** [comment]
Than we are sorry because we cannot help you in this case.
