### ISSUE TITLE
patchelf breaks ledger 2.6.3 rpaths

### ISSUE THREAD

**Issue by peti** [NixOS/patchelf#5]
When ledger 2.6.3 is built with `dontPatchELF = true`, it works just fine. If patchelf is run, however, it breaks the rpath of `libamounts.so.0` and `libledger-2.6.3.so`. Run 

```
ldd $out/bin/ledger
```

to see the broken paths.

**Comment by dezgeg** [comment]
This is fixed from the patchelf side in commit 48143414941d91016efca2b0ef6f32475d6eaa75.

A new release needs to be made though (and the parameter must be used in nixpkgs patchelf setup-hook).
