### ISSUE TITLE
Problem with patchelf and some security features

### ISSUE THREAD

**Issue by quantheory** [NixOS/patchelf#6]
There appears to be a problem with patchelf in hardened Gentoo. The problem is due to the "hole" put in some files, which is done in as described in this comment:

"As a workaround, make sure that the virtual address of our new
PT_LOAD segment relative to the first PT_LOAD segment is equal
to its offset"

In most cases this hole is getting very large (~18MB) and exceeds the maxSize, causing growFile to error out. It's not clear to me what specific feature is causing this. (ASLR is a common cause of bugs.)

**Comment by domenkozar** [comment]
Closing as too old.
