### ISSUE TITLE
Dynamic pageSize breaks (or exposes breakage) when patching foreign binaries

### ISSUE THREAD

**Issue by fsateler** [NixOS/patchelf#69]
#54 causes problems when patchelf is applied to a binary from other architecture, because the pagesize of the currently running kernel need not be the same for the binary in question. On ppc64el, the following tests fail (as of commit 63296c4e18381216f740670916608f9ef159672e):

```
FAIL: no-rpath-armel.sh
FAIL: no-rpath-armhf.sh
FAIL: no-rpath-hurd-i386.sh
FAIL: no-rpath-i386.sh
FAIL: no-rpath-kfreebsd-i386.sh
```

All of those fail with the same assertion:

    patchelf: patchelf.cc:695: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::rewriteSectionsExecutable() [with Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym]: Assertion `startAddr % getPageSize() == startOffset % getPageSize()' failed.

I'm not sure if the bug is introduced by #54 or just makes it more likely to happen due to sometimes pagesize being larger than 4096, or c4220eaf0f552cfd68148ddefd6455ff2ce0e08c should never really be expected to work, and the correct fix is to somehow get the pagesize from the binary currently being operated on.

It seems to me that patchelf expects the current binaries it operates on to match the current ABI, and that expectation is voided when run over foreign binaries.

CC @adevress @vdanjean

**Comment by domenkozar** [comment]
I'm getting the same. To reproduce:

```
$ wget https://dl.ngrok.com/ngrok_2.0.19_linux_amd64.zip
$ unzip ngrok_2.0.19_linux_amd64.zip
$ patchelf --set-interpreter /nix/store/y8scgsh8warhiy3pl39mqxyxphybcy7p-glibc-2.21/lib/ld-linux-x86-64.so.2 ./ngrok
patchelf: patchelf.cc:693: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::rewriteSectionsExecutable() [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym]: Assertion `(off_t) rdi(hdr->e_shoff) >= startOffset' failed.
Aborted
```

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by adevress** [comment]
> I'm not sure if the bug is introduced by #54 or just makes it more likely to happen due to sometimes pagesize being larger than 4096, or c4220ea should never really be expected to work, and the correct fix is to somehow get the pagesize from the binary currently being operated on.

Second solution I would say :)

This situation could not happen before #54 simply because it was not possible to generate a binary  for a platform with a pagesize different than 4096 before #54.

As the page size is independent of the architecture ( a ppc64 IBM machine can be 4096, 8K, 64K or even 1M in some case... ), it is not possible to hardcode a 1-1 mapping between pagesize and arch.

The only clean solution I see would be use the OS one by default and to add an option to specify manually the page size (--pagesize=4K)  in case of cross-platform patching.

**Comment by adevress** [comment]
Hi Eelco,

I have seen you reverted the patch.

We REALLY need the dynamic page size for our use case in HPC ( super computer or HPC cluster usage), the page size is almost never 4096 in HPC. Nix is simply not usable without it for us.

Would you accept to re-enable it if I provide a patch to manually specify page size in case of cross-patching ?
That would solve your issue for the MPISEL patching

**Comment by adevress** [comment]
Hi Eelco,

I forward you here what I commented on the closed ticket:

I have seen you reverted the patch.

We REALLY need the dynamic page size for our use case in HPC ( super
computer or HPC cluster usage), the page size is almost never 4096 in
HPC. Nix is simply not usable without it for us.

Would you accept to re-enable it if I provide a patch to manually
specify page size in case of cross-patching ?
That would solve your issue for the MPISEL patching


Adrien

**Comment by domenkozar** [comment]
@adevress I'm sure that having a flag to change the behavior would be accepted, if this change was accepted in the first place and then reverted due to bugs.

**Comment by fsateler** [comment]
@adevress @domenkozar I think the almost-best[1] solution is twofold:

1. Specify a default page size via a configure parameter. This can be obtained via `getconf PAGESIZE` or `getconf PAGE_SIZE`, which appears to be available in most unix-like systems (even on OSX). If no `getconf` is available, it can fall back to 4096.

2. Add a parameter to the patchelf binary to specify the page size to use. This will be useful for patching binaries of a foreign architecture.

[1] The real best would of course be to detect the pagesize of the binary in question.

**Comment by adevress** [comment]
Hi Felipe,

Thank you, it is exactly what I was meaning. I should have the time to
make you a patch for tomorrow.

Adrien
