### ISSUE TITLE
gcc -V not found

### ISSUE THREAD

**Issue by luisjosecosta** [NixOS/patchelf#71]
My patchelf build using gcc 4.8.3 is failing because gcc -V is no longer an option. I found [here](http://superuser.com/questions/846768/gcc-unrecognized-command-line-options-v-and-qversion-with-autoconf) that this option was removed around gcc 4.6. Using gcc 4.3.4 worked fine. My config.log file is attached.

[config.txt](https://github.com/NixOS/patchelf/files/82113/config.txt)

**Comment by edolstra** [comment]
Configure actually fails because of:
```
configure:2757: checking whether the C compiler works
configure:2779: gcc    conftest.c  >&5
/p/home/apps/gmpapp/gcc_dir/platform/gcc-4.8.4/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.4/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
```
which indicates a serious problem with your build environment.
