### ISSUE TITLE
fail aarch64 -- Need to detect page size from ELF file

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/patchelf#79]
```
make check
Making check in src
make[1]: Entering directory `/home/admin/nix-boot/patchelf-0.8/src'
make[1]: Nothing to be done for `check'.
make[1]: Leaving directory `/home/admin/nix-boot/patchelf-0.8/src'
Making check in tests
make[1]: Entering directory `/home/admin/nix-boot/patchelf-0.8/tests'
make  simple main main-scoped big-dynstr libfoo.so libfoo-scoped.so libbar.so libbar-scoped.so
make[2]: Entering directory `/home/admin/nix-boot/patchelf-0.8/tests'
make[2]: `simple' is up to date.
make[2]: `main' is up to date.
make[2]: `main-scoped' is up to date.
make[2]: `big-dynstr' is up to date.
make[2]: `libfoo.so' is up to date.
make[2]: `libfoo-scoped.so' is up to date.
make[2]: `libbar.so' is up to date.
make[2]: `libbar-scoped.so' is up to date.
make[2]: Leaving directory `/home/admin/nix-boot/patchelf-0.8/tests'
make  check-TESTS
make[2]: Entering directory `/home/admin/nix-boot/patchelf-0.8/tests'
make[3]: Entering directory `/home/admin/nix-boot/patchelf-0.8/tests'
PASS: plain-fail.sh
PASS: plain-run.sh
PASS: shrink-rpath.sh
PASS: set-interpreter-short.sh
FAIL: set-interpreter-long.sh
PASS: no-rpath.sh
FAIL: set-rpath.sh
FAIL: big-dynstr.sh
FAIL: set-rpath-library.sh
make[4]: Entering directory `/home/admin/nix-boot/patchelf-0.8/tests'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/admin/nix-boot/patchelf-0.8/tests'
============================================================================
Testsuite summary for patchelf 0.8
============================================================================
# TOTAL: 9
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/home/admin/nix-boot/patchelf-0.8/tests'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/admin/nix-boot/patchelf-0.8/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/admin/nix-boot/patchelf-0.8/tests'
make: *** [check-recursive] Error 1
```

**Comment by gitfoxi** [comment]
From HEAD

```
PASS: plain-run.sh
PASS: plain-fail.sh
PASS: set-interpreter-short.sh
PASS: shrink-rpath.sh
FAIL: set-interpreter-long.sh
PASS: soname.sh
FAIL: set-rpath.sh
FAIL: no-rpath.sh
FAIL: big-dynstr.sh
FAIL: set-rpath-library.sh
PASS: no-rpath-armel.sh
FAIL: no-rpath-kfreebsd-i386.sh
FAIL: no-rpath-amd64.sh
PASS: no-rpath-hurd-i386.sh
PASS: no-rpath-kfreebsd-amd64.sh
FAIL: no-rpath-i386.sh
PASS: no-rpath-armhf.sh
PASS: no-rpath-mipsel.sh
PASS: no-rpath-ia64.sh
PASS: no-rpath-mips.sh
PASS: no-rpath-s390.sh
PASS: no-rpath-powerpc.sh
PASS: no-rpath-sparc.sh
PASS: no-rpath-sh4.sh
```

**Comment by fsateler** [comment]
Does it fail if you try PR #73 ?

**Comment by gitfoxi** [comment]
I'll try it but it says it has to do with foreign binaries and I'm running native aarch64.

**Comment by gitfoxi** [comment]
PR #73 didn't affect the outcome.

**Comment by fsateler** [comment]
OK. I wondered because PowerPC64 also fails without #73 or something
similar (the page size is not 4096 as hardcoded currently).


On 17 February 2016 at 13:30, Michael Fox <notifications@github.com> wrote:

> PR #73 <https://github.com/NixOS/patchelf/pull/73> didn't affect the
> outcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/patchelf/issues/79#issuecomment-185284842>.
>



-- 

Saludos,
Felipe Sateler

**Comment by gitfoxi** [comment]
Flexible page size is definitely an issue for aarch64 so probably on the right track.

**Comment by gitfoxi** [comment]
One problem is just I'm running ubuntu and `/bin/sh` is not bash which test scripts seem to assume. I don't know why she did this to me.

**Comment by gitfoxi** [comment]
One thing that's real though (and critical for nix) is that set-interpreter-long makes a segfaulting program:

```
++ basename ./set-interpreter-long.sh .sh
+ SCRATCH=scratch/set-interpreter-long
+ ./simple
Hello World
++ ../src/patchelf --print-interpreter ./simple
+ oldInterpreter=/lib/ld-linux-aarch64.so.1
+ echo 'current interpreter is /lib/ld-linux-aarch64.so.1'
current interpreter is /lib/ld-linux-aarch64.so.1
++ uname
+ test Linux = Linux
+ echo 'running with explicit interpreter...'
running with explicit interpreter...
+ /lib/ld-linux-aarch64.so.1 ./simple
Hello World
+ rm -rf scratch/set-interpreter-long
+ mkdir -p scratch/set-interpreter-long
++ pwd
+ newInterpreter=/home/admin/nix-boot/patchelf2/tests/scratch/set-interpreter-long/iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
+ cp simple scratch/set-interpreter-long/
+ ../src/patchelf --set-interpreter /home/admin/nix-boot/patchelf2/tests/scratch/set-interpreter-long/iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii scratch/set-interpreter-long/simple
+ echo 'running with missing interpreter...'
running with missing interpreter...
+ scratch/set-interpreter-long/simple
./set-interpreter-long.sh: line 23: scratch/set-interpreter-long/simple: No such file or directory
+ echo 'running with new interpreter...'
running with new interpreter...
+ ln -s /lib/ld-linux-aarch64.so.1 /home/admin/nix-boot/patchelf2/tests/scratch/set-interpreter-long/iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
+ scratch/set-interpreter-long/simple
./set-interpreter-long.sh: line 30: 13767 Segmentation fault      ${SCRATCH}/simple
```

**Comment by gitfoxi** [comment]
Double checked with #73 and darn, no help.

**Comment by gitfoxi** [comment]
I have something that works here: #80

The problem is that it breaks cross-architecture patching of elfs. It only helps to make sure you use the page-size of the kernel you are currently running. So a native aarch64 can patch it's own elfs but x86 can't cross-build aarch64.

What we need
-------------------

Is to detect the kernel page size from the elf itself.

Can it be done? I was hoping not to have to learn too much about elfs today, but I guess that didn't work out for me. I'll find out and let you know.

The only other way would be to make target kernel page size an explicit parameter for patchelf. Not a big deal in itself, but updating all of nix/nixpkgs/nixos to support this is mind-boggling.

**Comment by fsateler** [comment]
Current master picks up the native page size at build time, and you can
specify the page size on the command line, but I thought that didn't work
for you?

**Comment by gitfoxi** [comment]
Relevant: https://www.kernel.org/doc/Documentation/arm64/memory.txt

> AArch64 Linux uses either 3 levels or 4 levels of translation tables
with the 4KB page configuration, allowing 39-bit (512GB) or 48-bit
(256TB) virtual addresses, respectively, for both user and kernel. With
64KB pages, only 2 levels of translation tables, allowing 42-bit (4TB)
virtual address, are used but the memory layout is the same.

http://man7.org/linux/man-pages/man5/elf.5.html

>  p_align     This member holds the value to which the segments are
                   aligned in memory and in the file.  Loadable process
                   segments must have congruent values for p_vaddr and
                   p_offset, modulo the page size.  Values of zero and one
                   mean no alignment is required.  Otherwise, p_align should
                   be a positive, integral power of two, and p_vaddr should
                   equal p_offset, modulo p_align.

**Comment by gitfoxi** [comment]
I did it! Hooray for me! #80 now passes all tests under aarch64 and amd64.

What's needed is:

* More extensive testing (I will build nixos under aarch64 eventually)
* More architectures added to getPageSize() function

It would be good to find a more elegant solution, but the thing for now is to use the machine type from the elf header to decide the page size.

**Comment by gitfoxi** [comment]
@fsateler I guess that works fine for me. I just didn't know about it.

However, I still think it will be more convenient if page size can be reliably predicted from the ELF file itself. I guess we're already discussing this in #80

**Comment by fsateler** [comment]
Well, the pagesize is determined at build time by the OS configuration, so
most use cases should be handled fine. Apparently there is no easy way to
determine the page size of a given elf binary, and this works enough for
me, so I've not looked further into it.

On 2 March 2016 at 16:39, Michael Fox <notifications@github.com> wrote:

> @fsateler <https://github.com/fsateler> I guess that works fine for me. I
> just didn't know about it.
>
> However, I still think it will be more convenient if page size can be
> reliably predicted from the ELF file itself. I guess we're already
> discussing this in #80 <https://github.com/NixOS/patchelf/pull/80>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/patchelf/issues/79#issuecomment-191391650>.
>



-- 

Saludos,
Felipe Sateler

**Comment by gitfoxi** [comment]
Most use cases are good, but I think the case of cross-compiling is broken.
The user needs to know what the target page size is and needs to know that
there's such thing as page size (I didn't).

My idea is to look at the target elf which is contained in the elf header
and make a conservative decision.

For example aarch64 can have 4k or 64k page size. It's conservative to just
use 64k since the target should work either way.

I might be missing something because I'm not sure all the ways patchelf
uses the page size. Seems like a lot of different things.


On Wed, Mar 2, 2016 at 11:47 AM, Felipe Sateler <notifications@github.com>
wrote:

> Well, the pagesize is determined at build time by the OS configuration, so
> most use cases should be handled fine. Apparently there is no easy way to
> determine the page size of a given elf binary, and this works enough for
> me, so I've not looked further into it.
>
> On 2 March 2016 at 16:39, Michael Fox <notifications@github.com> wrote:
>
> > @fsateler <https://github.com/fsateler> I guess that works fine for me.
> I
> > just didn't know about it.
> >
> > However, I still think it will be more convenient if page size can be
> > reliably predicted from the ELF file itself. I guess we're already
> > discussing this in #80 <https://github.com/NixOS/patchelf/pull/80>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/NixOS/patchelf/issues/79#issuecomment-191391650>.
> >
>
>
>
> --
>
> Saludos,
> Felipe Sateler
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/patchelf/issues/79#issuecomment-191395610>.
>



-- 

-
Michael

**Comment by domenkozar** [comment]
See https://github.com/NixOS/patchelf/pull/216
