### ISSUE TITLE
hardcoded maxSize?

### ISSUE THREAD

**Issue by efferre79** [NixOS/patchelf#88]
During a --set-rpath operation on a vmware binary (vmware-vmx-debug) I get a "maximum file size exceeded" error. After looking at the code I have seen that the maxSize is calculated adding 32MB to the file size. Is there any reason for this limit?

**Comment by aitzkora** [comment]
I observed also this limitation. I have to patch some file up to 1.4G, I think I will used a patched version of patchelf. Its name couild be patchpatchelf :smile:

**Comment by domenkozar** [comment]
Fixed in #256
