### ISSUE TITLE
is there any other dependency for patchelf

### ISSUE THREAD

**Issue by rkanavath** [NixOS/patchelf#91]
We were using patchelf 0.8. but we hit a bug about "working around a Linux kernel bug by creating a hole of".
It was already fixed here https://github.com/NixOS/patchelf/commit/f6886c2c33a1cf8771163919f3d20f6340c0ce38

For that, we tried to use latest 0.9 downloaded from github.com/releases and having some issues with configure.

Running bootstrap.sh says

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force --warnings=all
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing --warnings=all
configure.ac:4: option `color-tests' not recognized
autoreconf: automake failed with exit status: 1
```
I am wondering if we could make patchelf binaries simply with a gcc patchelf.cc -o patchelf -lc
https://github.com/NixOS/patchelf/issues/47

**Comment by fsateler** [comment]
You need a newer automake. Alternatively, remove the option color-tests from configure.ac

**Comment by edolstra** [comment]
Or download the release tarball (http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2), which should contain the generated autoconf files.
