### ISSUE TITLE
patchelf doesn't take arch into account when trimming rphath

### ISSUE THREAD

**Issue by obadz** [NixOS/patchelf#93]
I'll let @abbradar explain the issue since he's tracked it down but the main symptom is this:

```
$ nix-shell -p linuxPackages.virtualbox --pure --command VBoxManage
VBoxManage: error while loading shared libraries: libstdc++.so.6: wrong ELF class: ELFCLASS32
```

**Comment by abbradar** [comment]
I believe the issue is that patchelf trims "unused" RPATH paths not taking into account libraries' architecture. In this case, pre-`--shink-rpath`ed binary works fine and post-shrinked has 32-bit `libstdc++` in its RPATH only.
