### ISSUE TITLE
--set-rpath fails with “no version information available”, while exporting LD_LIBRARY_PATH works

### ISSUE THREAD

**Issue by michalrus** [NixOS/patchelf#99]
So I’ve got this expression to install [Transcribe!](http://www.seventhstring.com/xscribe/screenshots.html), that is distributed in binary form:

``` nix
super: self:

let

  libpath = super.lib.makeLibraryPath (with super; [
    stdenv.cc.cc glib gtk2 atk pango cairo gdk_pixbuf alsaLib
    xorg.libX11 xorg.libSM libpng12 gstreamer gst_plugins_base zlib
  ]);

in

super.stdenv.mkDerivation {
  name = "transcribe-8.40";

  src = super.fetchurl {
    url = "http://www.seventhstring.com/xscribe/downlinux64/xsc64setup.tar.gz";
    sha256 = "0fqs0f2p9kbp1skgqm5sgcq9xxf6rccbm22fvka8qmpvxpsxpcbs";
  };

  buildInputs = [ super.makeWrapper ];

  dontPatchELF = true;

  installPhase = ''
    mkdir -p $out/bin
    cp transcribe $out/bin

    patchelf \
      --set-interpreter "$(cat ${super.stdenv.cc}/nix-support/dynamic-linker)" \
      --set-rpath "${libpath}" \
      $out/bin/transcribe

    #wrapProgram $out/bin/transcribe \
    #  --set LD_LIBRARY_PATH "${libpath}"
  '';
}
```

When I run this, I’m getting:

```
% transcribe
transcribe: transcribe: no version information available (required by transcribe)
[…]
transcribe: transcribe: no version information available (required by transcribe)
transcribe: symbol lookup error: transcribe: undefined symbol:
(127)%
```

However, after removing `--set-rpath` and wrapping the program in a wrapper that exports `LD_LIBRARY_PATH` with what was previously passed to `--set-rpath`, the program launches.

Also, with `--set-rpath`, `ldd $(which transcribe)` returns lots of the exact error, `no version information available`. After setting a proper `LD_LIBRARY_PATH`, it shows correct paths.

The `RPATH` in original binary is empty.

How can I get this to work using `--set-rpath` only?

**Comment by probonopd** [comment]
I might be running into the same issue, https://github.com/probonopd/linuxdeployqt/issues/44

**Comment by domenkozar** [comment]
To solve this, don't run strip on resulting binary. `dontStrip = true;` in Nix.

I've tried using https://github.com/NixOS/patchelf/pull/127 and it didn't solve the issue.

**Comment by domenkozar** [comment]
Sadly this expression doesn't build anymore, but all the references issues have been fixed.

Make sure to come up with a way to reproduce this if the problem still exists.
